### ISSUE TITLE
vessel.maneuver.add doesn't fully add a manuever node KSP2 (0.2.0.0.30291)

### ISSUE THREAD

**Issue by ColJay** [untoldwind/KontrolSystem2#108]
Hi,

I'm using the latest build of KSP2 (0.2.0.0.30291) along with the latest updates through CKAN. Seems that when i call vessel.manuever.add a node is added but only partially.

By that i mean using the mod ManueverNode Controller i can see a node being present, but the game iteself I cannot interact with it. Nor does it seem that the command exec_next_node from std::vac execute the node - it fails with object reference not set.

I assume something fairly fundemental has changed in either KSP2 itself or perhaps Node Manager that Kontrol System 2 relies on?

Thanks for the great work!

**Comment by ColJay** [comment]
In addition to this - looks like vessel.maneuver.add_burn_vector does work correctly.

**Comment by untoldwind** [comment]
Yes in 0.2 an additional method call is necessary to correctly initialize the internal ManeuverNode.
Already fixed that for `add_burn_vector` and forgot about the other one ...

**Comment by untoldwind** [comment]
Should work in 0.5.1.2

**Comment by ColJay** [comment]
Seems to work great
