### ISSUE TITLE
Direction of angular momentum seems to reverse when i calculate it myself

### ISSUE THREAD

**Issue by ColJay** [untoldwind/KontrolSystem2#109]
Hi!

I'm running the following code:

const frame = vessel.orbit.reference_body.celestial_frame
const vel_vec = fn() -> vessel.orbital_velocity
const norm_vec = fn() -> vessel.position.normalized.cross(vel_vec().normalized) * vessel.position.magnitude
const rad_vec = fn() -> norm_vec().normalized.cross(vel_vec().normalized)

DEBUG.add_vector(fn() -> vessel.global_position, fn() ->  vel_vec().to_global(frame).normalized * vel_vec().magnitude * 10, GREEN,"Prograde" , 1)
DEBUG.add_vector(fn() -> vessel.global_position, fn() ->  norm_vec().to_global(frame).normalized * vel_vec().magnitude * 10, RED,"Normal" , 1)

expectation is to see the relevant velocity vectors traced out throughout the orbit for some debug info. Currently in a close to circular orbit round kerbin, eccenticity about 1 degree. 

I'm finding as i pass through the point on the orbit that is inline with kerbins velocity vector - the direction of the "norm" vector reverses. This is unexpected

Am I using the wrong vectors for the cross product or something? Docs seemed to indicate these are in the same reference frame.

**Comment by untoldwind** [comment]
I have to recheck, but I guess `frame` (resp. `vessel.orbit.reference_body.celestial_frame`) is not really a constant.

To be on the safe side: Instead of using `vessel.orbital_velocity.to_to_global(frame)` you could use `vessel.global_velocity` directly. Similarly `vessel.global_position` instead of `vessel.position.to_global(frame)` 

All the vector operations should work with the global variants just as well.

**Comment by ColJay** [comment]
Thanks for the response. I'll go back and try. I remember a few operations i couldn't do with the global vectors that i could with local ones, so i've been in favour of making sure i'm back in the local celestial frame for any vector operations. I'll double check where i came across issues and let you know. Thanks again!

**Comment by ColJay** [comment]
ok - so i've figured out my mistake. I'm taking the cross procut of the position not the relative vector from the body to the vessel. Using that instead, and still converting back to the local frame seems to be behaving as i'd expect. One of the things i was finding using global vectors and things directly - normalize isn't a thing. not sure if that's because they are always a unit vector??

**Comment by untoldwind** [comment]
I suppose the confusion with the global-variants is that there so many different types.

`vessel.global_position` returns a `GlobalPosition` which does not have a normalize, nor can they be multiplied with a scalar (as it represents a position in space).
But: Subtracting two `GlobalPosition` from each other (like `vessel.global_position - vessel.main_body.global_position` will give a `GlobalVector` which can be normalized, multiplied with a scalar and so on.
Also `GlobalPosition + GlobalVector` will result in a new `GlobalPosition`.

... I probably should write a dedicated documentation page for all of that ;)

**Comment by ColJay** [comment]
That does actually track with what i've been playing with, and would probably have figured it out - eventually. Thanks
