### ISSUE TITLE
Can we retrieve all currently predicted orbit patches?

### ISSUE THREAD

**Issue by ColJay** [untoldwind/KontrolSystem2#110]
Looking to validate some return flight path predictions, so i'm trying to retrieve the orbit patch post SOI change. EG - parking orbit around the Mun - add manuever node for a hyperbolic exit of the Mun soi back into Kerbin. The game shows the expected orbit around Kerbin - i'm trying to get those details directly. 

I think the original KOS allowed orbit:next_patch on any orbit object. I was wondering if there's anything similar? I've tried the manuecver, expected_orbit and orbit_patch - but these only deal with the current orbit pre and post manuever node.

Thanks!

**Comment by untoldwind** [comment]
The internal handling of maneuver nodes has changed quite a bit from KSP1. Additionally it looks like that there are some preparations for true n-body orbit types ... most likely for the future, but maybe one day it would be possible to park a telescope at the L2 Lagrange point of the Mun ...
In lack of a better technical term this makes the API a bit wonky.

After some experiments I came up with the following changes:
* There are four additional field on `Orbit`:
  * `start_transition`, `end_transition` representing the patch transition type at the start/end of the orbit
  * `previous_patch`, `next_patch` to access the previous/next patch (both are `Option<Orbit>`)
* There is an additional field `trajectory` on Vessel:
  * This contains all orbit patches of the current trajectory of the vessel.
  * This does not take maneuvering nodes into account. I.e. `vessel.trajectory` represents where the vessel will end up continuing it current course without intervention.
* To access the planed trajectory if all maneuvering nodes are executed successfully, there is a `vessel.maneuver.trajectory` field containing all the orbit patches
  * This list will always start after the first maneuver node.
  * I.e. if there are no planed maneuver nodes this list will be empty.
  
You can try this out with this pre-release: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.1.3
(probably needs a bit more testing)

**Comment by appenz** [comment]
Awesome, and makes transfers between celestial bodies vastly easier.

**Comment by untoldwind** [comment]
This is now part of the 0.5.2 release.
I also tweaked the `vessel.maneuver.add` and `vessel.maneuver.add_burn_vector` methods to support multiple maneuver nodes, i.e. the second node should now be on the orbit created by the first and so one (hopefully)

**Comment by ColJay** [comment]
Amazing work dude. Very impressed with the speed you can turn things around. Will crunch some numbers and give it a whirl - thanks again!!
