### ISSUE TITLE
Moving the timing of a Node inscript doesn't move the patch

### ISSUE THREAD

**Issue by ColJay** [untoldwind/KontrolSystem2#111]
If you get a reference to a maneuver node and update the ETA or the TIME associated with it - the game seems to update the position of the node - but the patch/path predictions don't move.

If you then run another script looking for and again updating the node - there's either no node to reference, or the orbit associtated with the node isn't defined properly.

in game this can be seen by the position of the Node no longer being in the same location as the patch.

![Screenshot 2024-01-09 213937](https://github.com/untoldwind/KontrolSystem2/assets/26343956/44867a94-c579-4673-bafc-0af0d08d87b5)

**Comment by untoldwind** [comment]
This is a tricky one. I think I found the correct helper functions, but I have to provide some fake data (... most likely this will break on one of the future updates of the game).

I prepared a pre-release for testing: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.2.1

**Comment by ColJay** [comment]
This release is closer for sure. At the moment I'm not seeing the next_orbit and other node/patch related data being updated internally during script execution. This is possibly due to the way i'm using the objects though - i'm not sure.

What i'm seeing at the moment is:

1) create a node
2) evaluate the periapsis of the transfer patch orbit after transition of SOI
3) adust the node eta to move earlier / later around the initial orbit to alter the ejection angle
4) use the existing node reference and re-evaluate the periapsis

What is seems is that the node reference i have doesn't update with the new values.

However - it no longer crashes the code when i run the script multiple times.

Should I be getting an entirely new handle on a new node before evaluating the change in periapsis?

Also - not a clue if it's helpful or not, but i am also using the ManeuverNodeController mod when doing manual tweaking. Don't know if the code from that would be any use?
https://github.com/XYZ3211/ManeuverNodeController

Thanks again for your work on this. Really cool mod :)

**Comment by untoldwind** [comment]
I released the version for now as it seems to address at least some issues.
Figuring out why the internal data is still outdated some time requires a bit more digging.

**Comment by untoldwind** [comment]
I am still trying to understand why this is happening, but at least I found a workaround.

Here is the test-script I am using: https://gist.github.com/untoldwind/35d4f3be519949a3e40e5b438bd8fa0d
What I do is have a vessel in orbit around the moon, manually create one maneuver and then run that multiple times to gradually increase the prograde until I get an escape orbit.
What I notice is: 
* If I add a `yield()` (or `sleep(0.1)`) after manipulating the node the data is consistent (i.e. the `escape` transition appears in the `vessel.maneuver.trajectory`). 
* If I do not do the `yield()` the `vessel.maneuver.trajectory` is the same as before the tweak of the maneuver node

So it looks like the game internally needs an Update cycle to reach a consistent state.

**Comment by untoldwind** [comment]
This is somewhat experimental: I tweaked the internals so that there is an implicit `yield()` after a change of the maneuver node properties.
For me this script seems to work now as expected: https://gist.github.com/untoldwind/109c1201cf4386649c7ac2a308f45482

**Comment by ColJay** [comment]
Hopefully get some time to play around with this over the weekend - will report back what i find.

Thanks.

**Comment by ColJay** [comment]
Hi. I think there's still something odd going on here, esp around the ETA and timing changes. 

I'm playing around with a seek to find the best ETA for the node to eject me into an orbit with a desired periapsis for Kerbin from Mun. I've calculated the required deltav, and am just aligning the node to correctly setup the escape. When i do this and push the ETA forwards/backwards in a loop seeking the target, things don't quite work out. It's as though some of the references to the objects reset themselves to earlier versions, or don't update at all.

If i run your script also and add in a change to the ETA as well as the exisitng vel changes, what i see is the last sets of outputs that are being written - looping through the "old" and the "new" nodes (lines ON and NN) - they are identical, which i don't think they should be. 

It's like the assigning of the variable to the vessel.maneuver.nodes is a reference to the nodes, which updates the "old" variable, and doesn't keep a copy of what it was originally. For me - this is meaning as I compare the orbit changes old to new, the numbers often don't reflect expectation, but the odd thing is - it's not always the case. I'm assuming something about how the game updates sometimes that tick resets everything - although i'm no programmer so not really sure what's going on

**Comment by ColJay** [comment]
Further testing - if i use a function to return the orbit of the node, and use that for my calcs - things seem to work out. So I have a solution to the issues i have been facing. I'm pretty sure i was doing something wrong also, but as it stands I think i can work with the nodes correctly

**Comment by untoldwind** [comment]
I included the changes in the 0.5.2.4 release.
And yes, the `.trajectory` fields return a snapshot of the current situation that is not automatically updated (there would be too many problems with game updates if this would be always up to date).

Have the check when the internal references to the `ManeuverNodeData` become invalid (and if there is way to detect it). E.g. if you delete a node there might be still a dangling reference in the script.
