### ISSUE TITLE
Request for documentation on user modules

### ISSUE THREAD

**Issue by Calaverah** [untoldwind/KontrolSystem2#112]
When attempting to access a public function from a local/user created to2 file, the compiler does not recognize the module being called. I'm sure it's user error as both the compiler and the VSextension are showing errors, however I'm not entirely sure where the issue is stemming from. I seem to be calling the method exactly as others have in past examples. For now the easy solution is to just include any needed functions directly in the file attempting to call them.

If the problem isn't user error, I can try and create a way to reproduce the issue later today. But for now, are there any examples or documentation in work that I can refer to?

EDIT: I forgot to mention that moving the modules to the std sub folder doesn't appear to have an affect as it did in a somewhat similar issue post previously.

**Comment by untoldwind** [comment]
Well there is this one: https://kontrolsystem2.readthedocs.io/en/latest/language/modules.html

Maybe it should be clarified that these rules also apply for the `to2Local` folder. So if you have files:
```
to2Local/
| - my_lib.to2
| - my_utils/
|   | - helpers.to2
```

with
my_lib.to2
```rust
pub fn my_lib_func() {
}
```
and
my_utils/helpers.to2
```rust
pub fn my_helper_func() {
}
```

Then you can do
```
use { my_lib_func } from my_lib
use { my_helper_func } from my_utils::helpers

pub fn main_flight(vessel: Vessel, max_rotations : float = 2.0) -> Result<Unit, string> = {
  my_lib_func()
  my_helper_func()
}

**Comment by Calaverah** [comment]
Weird, I thought my implementation followed this pretty closely. I'll copy this over and see if it gives the same error. Thanks!

**Comment by Calaverah** [comment]
Okay I was able to get the my_lib module to appear successfully in the compiler, however I'm still getting a redline in the actual VS extension.

**Comment by untoldwind** [comment]
Have you updated the vs plugin to the latest version (that is currently 0.0.13)?
There have been some issues with the previous versions in finding functions/types in other files

**Comment by Calaverah** [comment]
I have, I think I'm going to stick with self contained modules for now. I really don't know what I'm doing wrong/differently.

**Comment by untoldwind** [comment]
Can you provide an example that is not working for you?
