### ISSUE TITLE
Further Realism Implementation

### ISSUE THREAD

**Issue by Calaverah** [untoldwind/KontrolSystem2#115]
At some point we can expect an RO/RSS equivalent for KSP2. However, enjoying a lot of the systems design on this mod, I've been dreaming of ways to implement science progression and engineering requirements into Kontrol System 2.

### Craft requirements
With our probes and vehicles, most of the time we base our systems on given telemetry such as altitude from sea level, ground level, location and direction, etc. It would be interesting to require certain instruments on the craft to receive this data in a script. (Perhaps the early instruments would be big and cumbersome, while later tech tree nodes would unlock smaller versions and even combined packages to keep things fresh and less mundane).

### Planetary requirements
Additionally, and likely the bigger piece of this gameplay change, planetary data such as gravitational constants, planet radii, atmospheric density, or anything you can imagine data wise would require a probe or vehicle to record that information in an early level mission to such a body. (Think of the early planetary missions where fly bys led to orbiters and eventually landings/entry vehicles, or even the discovery of the Van Allen Belts).

Obviously this would become a part of the Ultra Nightmare difficulty of an already difficult version of the game that is RO/RSS but I think it adds a little bit of purpose to missions apart from a simple "we need engineering points to unlock new engines". Having a direct feed from your missions to your craft capabilities could be an exciting new way to play the game. I have no clue how this could actually be implemented (every variable becomes an Option? lol) and it would likely require so much cooperation with other mods that it might be impossible to realize but just thought I'd share the thought in case anyone felt the same way.

**Comment by untoldwind** [comment]
One idea might be to have some kind internal "permission" system for the `ksp::` bindings, so that it would be possible to maintain multiple blacklist (or whitelists) to different difficulties/tech requirements.

To flesh this out even further there probably should also be some sort of script-requirements system, so that one can keep track what scripts (or maybe even what functions) are available with the current settings.
