### ISSUE TITLE
Expected type which should match doesn't

### ISSUE THREAD

**Issue by lefouvert** [untoldwind/KontrolSystem2#118]
_version 0.5.2.4 (Ckan)_

I have some struggles to identify this one.
Even replicate it was a mess.

Let's say I have 4 files :
2 pairs of struct refering to another struct

_gitreport::foostructref.to2_
```rust
use { Vessel } from ksp::vessel
use { Barstructref } from gitreport::barstructref

pub struct Foostructref(vessel: Vessel) {
    ship: Vessel = vessel
    stage: Barstructref[] = (0..vessel.staging.total_count)
        .map(fn(s) -> Barstructref(vessel, s))
}

impl Foostructref {}
```
_gitreport::barstructref.to2_
```rust
use { Vessel, Part } from ksp::vessel

pub struct Barstructref(vessel : Vessel, stage: int) {
    ship : Vessel = vessel
    stage : int = stage
    engines: Part[] = vessel.parts
        .filter(fn(p) -> p.activation_stage == stage && p.engine_module.defined)
}

impl Barstructref {}
```
___
_gitreport::ship.to2_
```rust
use { Vessel } from ksp::vessel
use { Stage } from gitreport::stage

pub struct Ship(vessel: Vessel) {
    ship: Vessel = vessel
    stage: Stage[] = (0..vessel.staging.total_count)
        .map(fn(s) -> Stage(vessel, s))
}

impl Ship {}
```
_gitreport::stage.to2_
```rust
use { Vessel, Part } from ksp::vessel

pub struct Stage(vessel : Vessel, stage: int) {
    ship : Vessel = vessel
    stage : int = stage
    engines: Part[] = vessel.parts
        .filter(fn(p) -> p.activation_stage == stage && p.engine_module.defined)
}

impl Stage {}
```
___
I get this error
> Rebooted in 00:00:02.3172985
> ERROR: [gitreport\ship.to2(4, 1)] IncompatibleTypes Expected item stage of Ship to be a Stage[], found gitreport::stage::Stage[]

However, if I comment those lines
```rust
    // stage: Stage[] = (0..vessel.staging.total_count)
    //     .map(fn(s) -> Stage(vessel, s))
```
in _gitreport::ship.to2_

everything is fine :
> Rebooted in 00:00:02.5851348
> No errors

I don't know where it come from, but i'm pretty sure I didn't make a mistake in my code, since both pairs of files are very similar, and the foo/bar one don't pop me any compilation error.

_Edit : formatting_
_Edit : gramaticaly more fluent_

**Comment by lefouvert** [comment]
After reviewing the title of your commit, I get why it was so hard to reproduce. Files are simply scanned alphabetically!
A crappy workaround is to make the filename of the "calling" structure after the name of the "called" structure (until the fix comes out) ^^

**Comment by untoldwind** [comment]
Yes, the compilation has to be done in multiple passes since it is possible to reference something that is defined somewhere below in the file or in another file that has not been processed yet.
In this specific case: The struct was processed in the first pass, but the underlying type was still no fully build. As it turns out that the C# framework just returns `false` when using an `.IsAssignableFrom`

Should work now in 0.5.2.5

**Comment by lefouvert** [comment]
_version 0.5.3.0 (Git)_

Hi !

Got this one :

__gitreport::structreffoo.to2_
```rust
// ko : v0.5.3.0 issue #118
// ok :
pub type ThrustSituationConst = int

pub const ThrustSituation: (Current: ThrustSituationConst, CurrentAsOn: ThrustSituationConst, Max_Vac: ThrustSituationConst, Max_Atm: ThrustSituationConst, Min: ThrustSituationConst) = (
    Current: 2**0,
    CurrentAsOn: 2**1,
    Max_Vac: 2**2,
    Max_Atm: 2**3,
    Min: 2**4
)

const displayMode: Cell<ThrustSituationConst> = Cell(ThrustSituation.Current)

fn foobar() -> Unit = {
    displayMode.update(fn(current) -> {
        if(current == ThrustSituation.Current) {
            buttonSwitch.label = "Switch to 'Current as ON'"
            return ThrustSituation.CurrentAsOn
        }
        buttonSwitch.label = "Switch to 'Current'"
        return ThrustSituation.Current
    })
}
```

which gives us :
> Rebooted in 00:00:04.4371719
> ERROR: [_gitreport\structreffoo.to2(29, 16)] ArgumentMismatch
> Argument updater of 'Cell<int>.update' has to be a sync fn(int) -> int, but got sync fn(int) -> Unit

I would get it says me 
> Argument updater of 'Cell<int>.update' has to be a sync fn(int) -> int, but got sync fn(int) -> _ThrustSituationConst_

even if it works in many other situation, but since it qualify this as `Unit`, I think it's a anomaly :)

**Comment by untoldwind** [comment]
Yes, this is a bug, but I do not think it was introduced with the pre-release.

There was a similar bug with regular functions where a final `return` was interpreted as `Unit`, obviously I forgot to fix it for lambda functions as well.

Quick workaround:
```
displayMode.update(fn(current) -> {
        if(current == ThrustSituation.Current)
            return ThrustSituation.CurrentAsOn
        ThrustSituation.Current
    })
```
(i.e. drop the return at the end)
or even 
```
displayMode.update(fn(current) -> if(current == ThrustSituation.Current) ThrustSituation.CurrentAsOn else ThrustSituation.Current)
```

**Comment by lefouvert** [comment]
I think you are right, it's not introduced by the prerelease. I just mention the version I use to give you the most information I have if it could help you to catch what goes wrong.

As it's the first time I use a language where the last term is returned (I have recently learn it's pretty commun), my eyes and my way to write are not really use to catch it easily. But I would never imagine the use of explicit `return` word could lead to something less clear to the compiler than it's absence :).

Eh ! When I said you (issue 119) I didn't conscienciously notice the compiler struggle with `if/else`, this is a case where I initialy wrote if/else, then compiler get lost, then I rewrite it as you see it in this issue report ^^

Thank you for the workaround.
(I try to do less inline code because of to many 200+ characters lines, indentation out of the count. as you take a look at the _issue #125_ suggestion of code, you could see than the 'newExperiments' declaration go over 400 characters, and initialy, `locationComparison` wasn't outsourced. That was a 1K+ character line. I don't think it's readable or maintainable x) )

**Comment by untoldwind** [comment]
The original code
```
displayMode.update(fn(current) -> {
        if(current == ThrustSituation.Current)
            return ThrustSituation.CurrentAsOn
        return ThrustSituation.Current
    })
 ```
 Should now work with 0.5.3.1
