### ISSUE TITLE
Array of arrays passing to functions

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#12]
I don't know if it's a bug, or if I'm doing it wrong.

I'm unable to pass an array of arrays of floats to a function, though I'm able to pass an array of floats without a problem.

This works:
`use { CONSOLE } from ksp::console

pub fn main_flight() -> Result<Unit, string> = {
	CONSOLE.clear()
		
	let my_array = [1,2,3,4]
	print_array(my_array)	
}

pub fn print_array(input_array: int[]) -> Result<Unit, string> = {
	CONSOLE.print_line("Array print in function")  
	CONSOLE.print_line(input_array.to_string())  
}

`

This doesn't work, giving me an Expected ',' error.

`use { CONSOLE } from ksp::console

pub fn main_flight() -> Result<Unit, string> = {
	CONSOLE.clear()
		
	let my_array = [[1,2],[3,4]]
	print_array(my_array)	
}

pub fn print_array(input_array: int[][]) -> Result<Unit, string> = {
	CONSOLE.print_line("Array print in function")  
	CONSOLE.print_line(input_array.to_string())  
}`

**Comment by untoldwind** [comment]
Should be fixed now in the 0.1.7 release.

**Comment by untoldwind** [comment]
This is covered by unit tests now
