### ISSUE TITLE
Question about unity test

### ISSUE THREAD

**Issue by lefouvert** [untoldwind/KontrolSystem2#120]
_version 0.5.2.5 (Ckan)_

I saw than `core::testing` give use access to what seems to be tools for unity test.
Since it's a better practice to test our code, I want to give it a try.

So there is this function :
_console::unit.to2_
```rust
use { truncate } from core::math

const Sexagesimal: float = 60.0

pub fn hms(timespan: float) -> (hour: int, minute: int, second: float) = {
    // floor((t%B^n)÷B^(n-1)) where B is base and n is base shift
    return (
        hour: truncate(timespan / Sexagesimal**2).to_int,
        minute: truncate((timespan % Sexagesimal**2) / Sexagesimal).to_int,
        second: timespan % Sexagesimal
    )
}
```
As I want to test it, I made this very basic function (inspired from std::lambert_test) :
_test::console::unit.to2_
```rust
use * from core::testing
use * from console::unit

test fn hms_test() -> Unit = {
    const testcases: (expectedHour: int, expectedMinute: int, expectedSecond: float, givenTimespan: float)[] =[
        (expectedHour: 0, expectedMinute: 0, expectedSecond: 0.0, givenTimespan: 0.0),
        (expectedHour: 0, expectedMinute: 0, expectedSecond: 7.8493, givenTimespan: 7.8493),
        (expectedHour: 0, expectedMinute: 1, expectedSecond: 0.0, givenTimespan: 60.0),
        (expectedHour: 1, expectedMinute: 0, expectedSecond: 0.0, givenTimespan: 3600.0),
        (expectedHour: 0, expectedMinute: 2, expectedSecond: 0.0, givenTimespan: 120.0),
        (expectedHour: 2, expectedMinute: 0, expectedSecond: 0.0, givenTimespan: 7200.0),
        (expectedHour: 0, expectedMinute: 2, expectedSecond: 7.8493, givenTimespan: 127.8493),
        (expectedHour: 2, expectedMinute: 2, expectedSecond: 3.849032, givenTimespan: 7323.849032),
        (expectedHour: 3, expectedMinute: 5, expectedSecond: 47.56382901, givenTimespan: 11147.56382901),
        (expectedHour: 0, expectedMinute: 0, expectedSecond: 47.56382901, givenTimespan: 11147.56382901)
    ]

    for (testcase in testcases) {
        let (hour, minute, second) = hms(testcase.givenTimespan)
        assert_int(testcase.expectedHour, hour)
        assert_int(testcase.expectedMinute, minute)
        assert_float(testcase.expectedSecond, second, 1e-5)
        
        fail_test("hms() didn't meet requirement")
    }
}
}
```
the last test case `(expectedHour: 0, expectedMinute: 0, expectedSecond: 47.56382901, givenTimespan: 11147.56382901)` is obviously wrong  and should fail the test.

How could I run this test since it's not when code is compiled ?
When and where does `fail_test` prompt his message ?

**Comment by untoldwind** [comment]
Yes, the `core::testing` module and `test` functions are supposed to be used in unit tests.
At the moment these are only used as part of the build processes.
I.e. you will find a lot of to2 tests in these folders:
* https://github.com/untoldwind/KontrolSystem2/tree/master/TO2-Test/to2SelfTest
* https://github.com/untoldwind/KontrolSystem2/tree/master/TO2-Test/to2Core
* https://github.com/untoldwind/KontrolSystem2/tree/master/KSP2Runtime-Test/to2KSP

The corresponding test-runners are theses (which are themselves regular xunit tests):
* https://github.com/untoldwind/KontrolSystem2/blob/master/TO2-Test/TO2SelfTests.cs
* https://github.com/untoldwind/KontrolSystem2/blob/master/TO2-Test/TO2TestSuite.cs
* https://github.com/untoldwind/KontrolSystem2/blob/master/KSP2Runtime-Test/TO2TestSuite.cs
* ... and a special one for the `std::` modules: https://github.com/untoldwind/KontrolSystem2/blob/master/KSP2Runtime-Test/TO2StdTestSuite.cs

At the moment this is the only way to run to2-testsuits. I am not sure if it makes sense to add an in-game UI for this.
... maybe as an extension for the vscode plugin

**Comment by lefouvert** [comment]
How I'm supposed to implement new features to my code since you added custom unit tests D':`,
Now I have to test all my code !

(Joking, it's for the best)
