### ISSUE TITLE
Request for string methods

### ISSUE THREAD

**Issue by lefouvert** [untoldwind/KontrolSystem2#123]
_version 0.5.2.5 (Ckan)_

Hi !
It would be nice to have some methods which would allow us to build new string from some existent, with some methods as :
.replace
.substring (or slice ?)

or allow string to use some of the methods of the array (as map, map_with_index etc) which would nullify the need of new string methods.

Context :
I would like to have a «generic» entry point which would search in a mission folder one with a compatible module name (thanks to your implementation of MAINFRAME) based on ship name. However, as usual, KSP rename vessels with numerotatons suffixs, and spaces in module's name are interpreted as underscores.
This combined with the inability to build string with parts of other strings obliterate thoses wishes.
For exemple a .replace method could be use as 
```rust
const foo = bar.replace(" ", "_")
```
which could garantee strings are still unmutable, but allows to build strings from parts of other strings.

**Comment by untoldwind** [comment]
Added `index_of`, `slice`, `replace` and `split` in 0.5.2.6

**Comment by lefouvert** [comment]
Many thanks :)
