### ISSUE TITLE
Request for CONSOLE tweaking

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#129]
Hi.
I wanted to know if it was possible to add method to open/close automatically the CONSOLE and to add a couple of R/W variables to change the height and the width of the CONSOLE.
Thanks :)

**Comment by untoldwind** [comment]
I wanted to keep the `CONSOLE`  independent of the window displaying it as there is still the possibility to display it in a different manner (e.g. in kOS there was a way to connect to it via telnet).

But I added a `CONSOLE_WINDOW` to `ksp::ui` to control it the same way I recently introduced for scripted UI-windows.

So in the next release there will be:
* `CONSOLE_WINDOW.open()`
* `CONSOLE_WINDOW.close()`
* `CONSOLE_WINDOW.center()`
* `CONSOLE_WINDOW.is_closed`
* `CONSOLE_WINDOW.size`
* `CONSOLE_WINDOW.min_size`
* `CONSOLE_WINDOW.position`

**Comment by PhilouDS** [comment]
Thank you very much!

**Comment by lefouvert** [comment]
My heart skip a beat at the idea of reintroducing telnet console :) (And I have to admit ingame console appearance control is a nice touch).

**Comment by untoldwind** [comment]
In 0.5.3.2 this should work:
```
use { Vessel } from ksp::vessel
use { CONSOLE_WINDOW } from ksp::ui

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
    CONSOLE.clear()

    CONSOLE_WINDOW.open()
    CONSOLE_WINDOW.center()
}
```

As for the telnet (or other type) console: I am still hesitant to put this into the main mod since doing networking might be frowned upon (if I remember correctly this kOS mod for KSP1 had an elaborate opt-in dialog for this).
But maybe this could be done with an optional addon that has KontrolSystem2 as a dependency.

**Comment by PhilouDS** [comment]
I just tried inside the VAB, it's wonderful!
I never used telnet with kOS so I can't say.
Thanks again fr your work.
