### ISSUE TITLE
method pertubed_orbit and expected_orbit

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#131]
Hi.
I don't understand why pertubed_orbit and expected_orbit doesn't have the same result. Is it normal?
```
CONSOLE.clear()

const this_obt = vessel.orbit

CONSOLE.print_line(this_obt.eccentricity.to_fixed(6))
CONSOLE.print_line(this_obt.periapsis.to_fixed(0))
CONSOLE.print_line(this_obt.apoapsis.value.to_fixed(6))
CONSOLE.move_cursor(CONSOLE.cursor_row + 1,0)

let temp_obt = this_obt.perturbed_orbit(this_obt.next_periapsis_time(), vec3(0,0,500))
let new_node = vessel.maneuver.add_burn_vector(this_obt.next_periapsis_time(), vec3(0,0,500)).value

CONSOLE.print_line(temp_obt.eccentricity.to_fixed(6))
CONSOLE.print_line(temp_obt.periapsis.to_fixed(0))
CONSOLE.print_line(temp_obt.apoapsis.value.to_fixed(0))
CONSOLE.move_cursor(CONSOLE.cursor_row + 1,0)

 temp_obt = new_node.expected_orbit

CONSOLE.print_line(temp_obt.eccentricity.to_fixed(6))
CONSOLE.print_line(temp_obt.periapsis.to_fixed(0))
CONSOLE.print_line(temp_obt.apoapsis.value.to_fixed(0))
```

**Comment by untoldwind** [comment]
This is mostly a problem with the documentation and something of a leftover from KSP1.
`orbit.perturbed_orbit` applies the delta-v instantaneously, i.e. the resulting orbit is as if the vessel from one moment to the next changed its velocity, which is mostly how it was done in KSP1.
`vessel.maneuver.add_burn_vector` actually takes the TWR (and thereby the required burn-time) of the vessel into account.

So:
* For small delta-v both functions should produce roughly the same result.
* For larger delta-v it highly depends on the type of engine the vessel is using, i.e. a low-thrust xenon-engine will have a much different result than a big booster stage.

One of the benefits of `orbit.perturbed_orbit` is that it is really fast compared to `vessel.maneuver.add_burn_vector` (under the hood there a differential equation has be solved). So if you are doing orbit optimizations it might be feasible of first find a close enough solution with `orbit.perturbed_orbit` and then fine-tune it with `vessel.maneuver.add_burn_vector`

**Comment by PhilouDS** [comment]
Ok, thank you for your explanation!

**Comment by PhilouDS** [comment]
Hello @untoldwind 
I'm back to this conversation about `perturbed_orbit`.
I have a craft in a transition orbit going from Kerbin to the Mun. I'm trying to make an algorithm to change the inclination of the orbit around the Mun using `perturbed_orbit`. But...
`ship.orbit.next_patch.defined` returns `true` whereas
`ship.orbit.perturbed_orbit(t0, vec3(0,0,0)).next_patch.defined` returns `false` 🤔 
Any ideas about the reason of that?

I have a functionnal algorithm using maneuver nodes but it's very slow. That's why I wanted to use `perturbed_orbit`. Also, what's the difference between `node.expected_orbit` and `node.orbit_patch`?

Thank you for your time.

**Comment by untoldwind** [comment]
It probably would be a good idea make a clean separation between trajectories and orbits in the API, in the sense that:
* A trajectory is something attached to a vessel that might consist out of multiple orbit patches (separated by events like Start -> SOI change -> Crash)
* An orbit is ... well ... just a Kepler orbit around a reference body, is not attached to anything and does not take any collisions or SOIs into account. I.e. just a helper for Kepler math.

`orbit.perturbed_orbit` and `body.create_orbit` create the latter and as such have neither a `next_patch` nor `prev_patch`. For these to be filled out the orbit has to run through the PatchedConicsSolver of the game, which is a quiet expensive operation.

As for the maneuver node: Documentation should be fixed (or actually be written in the first place :sweat_smile:).
* `node.orbit_patch` is supposed to be the orbit patch the node is defined/executed on (i.e. part of the current trajectory of the vessel)
* `node.expected_orbit` should be the orbit patch after the node has been executed (i.e. the future trajectory of the vessel when/if the maneuver has been performed)

**Comment by PhilouDS** [comment]
Thanks for your quick and clear answer, as always 😉

**Comment by untoldwind** [comment]
I reworked the API in 0.5.7.5 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.7.5), which (hopefully) should make this clearer now.

* `vessel.trajectory` and `vessel.maneuver.trajectory` now return a `ksp::orbit::Trajectory`, which behaves (mostly) like an array of `ksp::orbit::OrbitPatch`
* A `OrbitPatch` is always part of a trajectory and is an extension of `Orbit`
* `start_ut`, `end_ut`, `start_transition`, `ent_transition` have be removed from `Orbit` and are now part of `OrbitPatch`

**Comment by PhilouDS** [comment]
Thanks. I see in the documentation that `vessel.orbit` returns now the type `OrbitPatch`. BUt `body.orbit` returns the type `Orbit`. Is this just a mistake or is there a reason for that. Also, except for `body.orbit`, does the type `Orbit` is still used?

**Comment by untoldwind** [comment]
That is kind of by design, because celestial bodies currently just have an orbit (with not start or end) and not a trajectory ... maybe that will be change when/if asteriods are added to the game (which may have SOI changes and might crash into something).
I will update the API then ... most likely though asteroids will become their own thing considering that in KSP1 you could essentially convert them into vessels.

**Comment by lefouvert** [comment]
Hû, maybe I'm wrong, but does thoses change make us lost the access to the orbit, type of `ksp::orbit::Orbit`, of the vessel ?
Since the `OrbitPatch` is available in `Trajectory`, I didn't expect than vessel lost his orbit, without any kind of perturation/maneuver.
I'm one of thoses people who likes generalization cascade more than exclusive specialisation. «A vessel is a body, an orbit patch is an orbit», etc :)
Don't hesitate to say me if it's a bad idea a vessel board with thoses two aspect : Orbit + OrbitPatch (via trajectory).

**Comment by untoldwind** [comment]
`vessel.orbit` should still exists (unless there is a bug I have not noticed).
The only difference is that `vessel.orbit` now returns an `OrbitPatch`, which should have all the same properties as before.

An `OrbitPatch` is a extension an `Orbit`, i.e. its pretty much the same, just with these additional fields:
* `start_ut`, `end_ut`, `start_transition`, `end_transition`
* `trajectory`, i.e. the trajectory it belongs to. In case of the vessel `vessel.orbit.trajectory` should be the same as `vessel.trajectory`

The only breaking change is that `body.orbit` and `orbit.perturbed_orbit` do not have the above fields any more

**Comment by lefouvert** [comment]
True true true true.
I was just caught off guard when I had to change 
```rust
        let referenceOrbit = vessel.orbit
        while(referenceOrbit.reference_body.parent_body.defined)
            referenceOrbit = referenceOrbit.reference_body.orbit
```
into
```rust
        let referenceOrbit = vessel.main_body.create_orbit(vessel.position, vessel.orbital_velocity, current_time())
        while(referenceOrbit.reference_body.parent_body.defined)
            referenceOrbit = referenceOrbit.reference_body.orbit
```
because of type change.

(Thoses line should give me the orbit of first child orbiting the star, ie Kerbin's orbit if I'm orbiting Mun; Jool's orbit, if I'm orbiting Laythe, or Duna's orbit if i'm orbiting... Duna :) )

**Comment by lefouvert** [comment]
Oh !
I'm (really strongly) happy to learn than `OrbitPatch` is able to be shrink into an `Orbit`. The example is only because it's how I notice it, as you seen, I found a workaround. This question was more about «the philosophy» than the work around. But since `OrbitPatch` is shrinkable, all my wishes are granted :)

Same trajectory (about philosophy, not about vessel :D), does `Vessel` type is able to be shrink into a `Body` type ? I gess not since `ksp::vessel::Targetable` board both `body` and `vessel`. It's not an issue, only a question ^^

**Comment by untoldwind** [comment]
Well a `Vessel` is not a `Body`, but both are `Tragetable` (as is a docking port of a vessel btw).
So it should be possible to assign all of them to a variable of type `Targetable`.
