### ISSUE TITLE
VSC extension - Improvement

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#135]
VSIX version: 0.0.30

I'm starting a new issue topic here to list issues encountered with VSCode extension.

version 0.0.30 doesn't like `.value` or `.success` for result<>
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/11844822-7f04-461c-a59f-256d0009b360)

**Comment by untoldwind** [comment]
Should be fixed in:
https://github.com/untoldwind/KontrolSystem2/releases/download/v0.5.5.3/to2-syntax-0.0.31.vsix

**Comment by PhilouDS** [comment]
version 0.0.31

`reaction_wheel` not defined for ObjectAssemblyPart (thanks for the documentation update).

![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/6dc21391-302d-40c2-a5a2-1b6d927eeef6)

**Comment by untoldwind** [comment]
Should be included in 0.0.32 of the latest pre-release
