### ISSUE TITLE
Enhancement for later: LOG to TXT or CSV file

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#144]
I'd like to have a function like `LOG` in kOS to write in an extern file and create a TXT or a CSV file. I created log mission with kOS and it's cool to have a sort of history folder. (example below of a (french) mission with KSRSS in a career mode).

CSV files are great too for different purposes.
But I really understand this is not a priority right now.

[S16-RovL1.txt](https://github.com/untoldwind/KontrolSystem2/files/14626911/S16-RovL1.txt)

**Comment by untoldwind** [comment]
I guess having a script specific log (just like `CONSOLE`) would not be all that complicated.

What would be the preferred way of storage?

* Next to the the `.to2` file?
  * I.e. if you have a `my_flight_control.to2` there would be a `my_flight_control.log` next to it when you write something to the log
* Everything in a separate `log` folder next to `to2Local`
  * This way you could name the log-files whatever

As for CSV: There are just too many flavors out there. Would something more structured like json be ok as well?

**Comment by PhilouDS** [comment]
> What would be the preferred way of storage?
> 
> * Next to the the `.to2` file?
>   
>   * I.e. if you have a `my_flight_control.to2` there would be a `my_flight_control.log` next to it when you write something to the log
> * Everything in a separate `log` folder next to `to2Local`

I guess it would be great to specify a folder inside the `to2local`. For exemple `log vessel.altitude_sealevel in folder_name/file_name.txt`. The default folder could be `to2Local` and the defaut file name `vessel.name`.
 
> As for CSV: There are just too many flavors out there. Would something more structured like json be ok as well?
For the csv file, I use it just like a txt file with comma separation. The idea is then to save the text file but a CSV extension.
 For exemple
```
while (vessel.altitude_level < 1000) {
  log current_time() + "," vessel.altitude_sealevel +"," + vessel.vertical_velocity in folder_name/file_name.csv`
  sleep(0.1)
}
```
I don't use json files. tbh, I don't really understand how they work. CSV files seem to be easier to use.

**Comment by lefouvert** [comment]
@untoldwind I can only agreed with the idea to have a controled space (anywhere you think it's good, the purpose is just to have access) where you can create, read and append text files. Cherry on the cake would be to be able to create and browse folders (still in this controled space)
I think you shouldn't care about file type since json, csv, xml etc are just text files with conventions. Maybe i'm overconfident, but I think if we want a convention, it's up to us to make the implementation we want.
The controled space is up to you, but I think 'to2Local' can be a good idea.

(for my usage, it's mostly log files, and default configuration files. And _MAYBE_ if I dont find a better way to be able to communicate between satelite in a satelite constellation launch)

@PhilouDS Json is just a way to hierachicaly organize (and transmit) data. You have some 'names' which relate to a data. The data can be a value, an array, a string, or other 'names'. Think about it as computer folder : A folder can contain text files,  other kind of files, or other folders. It's oversimplified, but the idea is here.

**Comment by untoldwind** [comment]
I added basic support for that to the 0.5.7.1 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.7.1) pre-release. Had to be somewhat careful to do the file IO as async as possible.

Very simple test:
```
use { Vessel } from ksp::vessel
use { sleep } from ksp::game
use { MAIN_LOG } from ksp::debug

pub fn main_flight(vessel: Vessel) -> Result<Unit> = {
   MAIN_LOG.truncate() // this will clean the existing file, skip it if log should just append to existing one
   
    while(true) {
        log.log($"{vessel.position}")
        sleep(0.1)
    }   
}
```

Additionally there is also an `open_log_file` function to create additional files. `MAIN_LOG` is based on the script-name, because vessel name might not be unique (or there might not be a vessel in the first place)

**Comment by PhilouDS** [comment]
I tried this script and converted the log file in a CSV file and this works very fine!!

```
use { Vessel } from ksp::vessel
use { sleep, wait_until, current_time } from ksp::game
use { MAIN_LOG } from ksp::debug

pub fn main_flight(vessel: Vessel) -> Result<Unit> = {
   MAIN_LOG.truncate() // this will clean the existing file, skip it if log should just append to existing one
   MAIN_LOG.log("Mission Time ; Altitude ; Vertical Velocity")

   wait_until(fn() -> vessel.vertical_speed > 1)
   const t0 = current_time()
   sleep(0.1)

    while(vessel.altitude_sealevel < 5000) {
        MAIN_LOG.log($"{current_time() - t0:N1} ; {vessel.altitude_sealevel:N2} ; {vessel.vertical_speed:N2}")
        sleep(0.1)
    }   
}
```

![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/dc19d51a-3f52-45a7-8d16-da4aa40bb061)


I see just one tiny problem: the script you're running can't be in a subfolder of `to2_local`.

**Comment by PhilouDS** [comment]
BTW, is it possible to have access to a field `mission_time` for `vessel`? In kOS `MissionTime` wasn't attach to a vessel. It was a global variable.

**Comment by untoldwind** [comment]
In pre-release 0.5.7.2:
* `vessel.has_launched`, `vessel.launch_time` and `vessel.time_since_launch` (the latter should be the mission time)
* `MAIN_LOG` should now work for scripts in sub-directories as well (logs will bis still in the `to2Local/logs` folder, but get a prefix in the filename)

**Comment by PhilouDS** [comment]
This works perfectly fine! Thanks.

**Comment by PhilouDS** [comment]
My first log mission with to2 :) For now, I'm using the same template I had with kOS but maybe, it will change someday.

![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/0b7d9a5f-cf6e-4981-a7de-4f5a2d33ea8a)

**Comment by lefouvert** [comment]
Hi !
Does the ability to read to log file could be frown uppon, or it is a conceavable feature ?
I would like to peek some info inside to know if I should start a new one or  append the existent one.
Or even better, be able to choose to clear the console and display the logs on it.

**Comment by untoldwind** [comment]
I guess reading from the extension folder is ok. So in 0.5.8.4 the `ksp::debug::LogFile` now has a `read_lines()` method.

**Comment by PhilouDS** [comment]
> I guess reading from the extension folder is ok. So in 0.5.8.4 the `ksp::debug::LogFile` now has a `read_lines()` method.

Hi. The last released version of kontrol system in github is 0.5.8.4. But in CKAN and Spacedock, the version is numbered 0.5.**9**.4. Is it normal?

**Comment by PhilouDS** [comment]
> I guess reading from the extension folder is ok. So in 0.5.8.4 the `ksp::debug::LogFile` now has a `read_lines()` method.

d

**Comment by PhilouDS** [comment]
> `ksp::debug::LogFile` now has a `read_lines()` method.

`read_lines()` gives a list of strings. That's okay but, is it possible to convert a string into a float?

**Comment by lefouvert** [comment]
What a coincidence... :)

file _ui::constant.to2_
```rust
pub type StringConst = int

pub const String: (Backslash: string, DoubleQuote: string, Quote: string, LineBreak: string, CarriageReturn: string, Tab: string, Space: string, Hyphen: string, Underscore: string, Empty: string, IsEmpty: StringConst, First: StringConst) = (
    Backslash: "\\",
    DoubleQuote: "\"",
    Quote: "'",
    LineBreak: "\n",
    CarriageReturn: "\r",
    Tab: "\t",
    Space: " ",
    Hyphen:"-",
    Underscore: "_",
    Empty: "",
    IsEmpty: 0,
    First: 0
)
```

file _math::constant.to2_
```rust
pub type ArrayConst = int

pub const Array: (IsEmpty: ArrayConst, First: ArrayConst) = (
    IsEmpty: 0,
    First: 0
)
```

file _ui::string.to2_
```rust
use { pow } from core::math

use { Array } from math::constant
use { String } from ui::constant

pub struct String(str: string, decimalChar: string = ".") {
    str: string = str
    charified: string[] = charify(str)
    decimal: string = decimalChar
}

impl String {
    fn trim(self) -> string =
        charify(self.trim_right())
            .reduce(String.Empty, fn(res, c) -> if(c != " " || res.length > 0) res + c else res)

    fn trim_left(self) -> string =
        self.charified
            .reduce(String.Empty, fn(res, c) -> if(c != " " || res.length > 0) res + c else res)

    fn trim_right(self) -> string =
        self.charified
            .reverse()
            .reduce(String.Empty, fn(res, c) -> if(c != " " || res.length > 0) c + res else res)

    fn to_float(self) -> Option<float> = {
        let res = 0.0
        let shift = 0
        let neg = false
        let dec = Some(0)
        let exp = if(false) 0.0
        let result = 0.0
        const input = self.charified
            .reverse()
        for(i in 0..input.length) {
            let read = ("0123456789eE-" + self.decimal).index_of(input[i])
            if (read < 10) { // digit
                res += (read * pow(10, shift))
            } else if (read == 12) { // minus
                if (neg)
                    return None()
                res *= -1.0
                neg = true
            } else if (read == 13){ // dot
                if(!dec.defined)
                    return None()
                else {
                    res *= pow(10, - dec.value)
                    dec = if(false) 0
                    shift = -1
                }
            } else if(read == 10 || read == 11) { // e E
                if(exp.defined)
                    return None()
                else {
                    exp = Some(res)
                    res = 0.0
                    neg = false
                    dec = Some(-1)
                    shift = -1
                }
            } else { // anything else
                return None()
            }
            shift += 1
            if(dec.defined)
                dec = Some(dec.value + 1)
        }
        Some(if(exp.defined) res * pow(10, exp.value) else res)
        if(exp.defined) 
            return Some(res * pow(10, exp.value))
        else
            return Some(res)
    }

    fn to_int(self) -> Option<int> = {
        const res = self.to_float()
        if(res.defined)
            res.value.to_int
    }

}

sync fn charify(str: string) -> string[] = {
    const str_const = str
    (0..str.length).reduce(<string>[], fn(res, i) -> res + str_const.slice(i, i + 1))
}
```

However, @untoldwind , I don't understand how `1.2345` is different from `1.2345` :
```rust
use * from core::testing
use * from ui::string

test fn string_test() -> Unit = {
    assert_string("   toto", String("   toto").trim_right())
    assert_string("   toto", String("   toto   ").trim_right())
    assert_string("toto", String("toto   ").trim_right())
    assert_string("   toto   toto", String("   toto   toto").trim_right())
    assert_string("   toto   toto", String("   toto   toto   ").trim_right())
    assert_string("toto   toto", String("toto   toto   ").trim_right())
    assert_string("", String("   ").trim_right())

    assert_string("toto", String("   toto").trim_left())
    assert_string("toto   ", String("   toto   ").trim_left())
    assert_string("toto   ", String("toto   ").trim_left())
    assert_string("toto   toto", String("   toto   toto").trim_left())
    assert_string("toto   toto   ", String("   toto   toto   ").trim_left())
    assert_string("toto   toto   ", String("toto   toto   ").trim_left())
    assert_string("", String("   ").trim_left())

    assert_string("toto", String("   toto").trim())
    assert_string("toto", String("   toto   ").trim())
    assert_string("toto", String("toto   ").trim())
    assert_string("toto   toto", String("   toto   toto").trim())
    assert_string("toto   toto", String("   toto   toto   ").trim())
    assert_string("toto   toto", String("toto   toto   ").trim())
    assert_string("", String("   ").trim())

    assert_some(1234.0, String("1234").to_float())
    assert_some(1234.0, String("1234.0").to_float())
    assert_some(1234.125, String("1234.125").to_float())
    assert_some(0.125, String(".125").to_float())
    assert_some(0.125, String("0.125").to_float())
    assert_some(12300.0, String("123e2").to_float())
    assert_some(12300.0, String("123E2").to_float())
    assert_some(12345.0, String("123.45E2").to_float())
    assert_some(0.0, String("0.0E-0.0").to_float())
    assert_some(1.2345, String("123.45E-2").to_float())
    assert_some(1.2345, String("123.45E-2.0").to_float())
    assert_some(0.3903833177147786, String("123.45E-2.5").to_float())

    assert_some(-1234.0, String("-1234").to_float())
    assert_some(-1234.0, String("-1234.0").to_float())
    assert_some(-1234.125, String("-1234.125").to_float())
    assert_some(-0.125, String("-.125").to_float())
    assert_some(-0.125, String("-0.125").to_float())
    assert_some(-12300.0, String("-123e2").to_float())
    assert_some(-12300.0, String("-123E2").to_float())
    assert_some(-12345.0, String("-123.45E2").to_float())
    assert_some(-0.0, String("-0.0E-0.0").to_float())
    assert_some(-1.2345, String("-123.45E-2").to_float())
    assert_some(-1.2345, String("-123.45E-2.0").to_float())
    assert_some(-0.3903833177147786, String("-123.45E-2.5").to_float())
}
```
give me
> $> test
...
Module ui::test::test_string
  ui::test::test_string::string_test ......................... Failure (after 31 assertions)
     assert_some: Some(1.2345) != Some(KontrolSystem.TO2.Runtime.Option`1[[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]])

which correspond to `assert_some(1.2345, String("123.45E-2").to_float())`
however, at runtime, with `ksp::console::CONSOLE.print_line(ui::string::String("123.45E-2").to_float().value.to_string())`, I get a nice
> `1.2345`

What's wrong ?

**Comment by untoldwind** [comment]
> Hi. The last released version of kontrol system in github is 0.5.8.4. But in CKAN and Spacedock, the version is numbered 0.5.**9**.4. Is it normal?

Seems like I made a typo when uploading the version to spacedock. The internally the version should be reported as 0.5.8.4
I will be more careful next time ;)

> Also, latest version of vsix (v 0.0.50) doesn't recognize `read_lines()` method.

The `read_lines` should be documented in the reference.json that is now part of the release.
There is now a reference json setting for the vscode extension, can you check if that points to the correct file?
I was hoping to be able to avoid re-releasing the extension with every minor update this way

**Comment by untoldwind** [comment]
@lefouvert 
> assert_some: Some(1.2345) != Some(KontrolSystem.TO2.Runtime.Option`1[[System.Double, mscorlib, Version=4.0.0.0,  Culture=neutral, PublicKeyToken=b77a5c561934e089]])

If the other `assert_some` are working correctly then it is most likely a funny rounding issue. Comparing floats with strict equals is inherently unstable, that is why the `assert_float` has an optional `delta` parameters (which is `1e-10` be default)
The IEEEE-754 standard is a really funny read ;)

**Comment by lefouvert** [comment]
Ugh... I was expecting with such few decimal digit, thoses kind of approximation would be mitigated. (and seen with the `to_string()`)
I learn recently (Jan 2023 ?) than this Delta is usualy called Epsilon in math vocabulary when a friend have seen my «almost_equal» function (and he made fun on me, grrr xD).
Let's go for some readings of the IEEEE-754 standard.
(Hum, should I use an
```rust
const foo = String("123.45E-2").to_float()
assert_true(foo.defined)
if(foo.defined)
    assert_float(1.2345, foo.value, 1e-5)
```
to get a reliable way to test `<float>Option` ?

**Comment by untoldwind** [comment]
I re-bundled the vscode extension, which should hopefully fix the problem: https://github.com/untoldwind/KontrolSystem2/releases/download/v0.5.8.5/to2-syntax-0.0.51.vsix

I also added `.to_int()` and `.to_float()` methods to strings, which return a result (in case the string does not contain a parseable number ).

**Comment by untoldwind** [comment]
@lefouvert 
I guess the `1e-10` default should work in most cases ... and yes, it probably should have been named epsilon, but in physics there is usually a delta ... also it looks nice to have little triangles in your formulas ;)

**Comment by lefouvert** [comment]
It's fun how you make a lot of tools I build obsolete with time. It's not a complain ! I really enjoy the situation. And I note we share some similar kinks : one of my biggest frustration on my keyboard is not having a layout with a  `Δ` key !
Puuuurrrfection would be having a layout giving access to all grek alphabet, but the one I miss the most is definilively delta ^^.
(And I won't blame you for using delta instead epsilon, I learn it really recently, it's only about sharing. And this friend is out of my league considering programmation knowledges. The kind of guys which daily reads patch notes for at least 4 programing languages, and is up to date for about ten of them -still at least- .When he is not caring about programmation skills, he reads physics or math books 'to relax'. I, when I want to rest, I play with Lego bricks... We are not all build the same way ^^)

**Comment by PhilouDS** [comment]
>Puuuurrrfection would be having a layout giving access to all grek alphabet, but the one I miss the most is definilively delta ^^. 

Press the Window key on your keyboard and then the "." key (with the Window key still pushed down). You'll have access to emoticons and also greek letters (and lot of symbols) 😎 αΔδβε ∬π

**Comment by PhilouDS** [comment]
@untoldwind This is weird. Visual Studio still doesn't recognize `read_lines()`.
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/0ce5e375-3f6b-47cf-8650-bc3334486fd7)

But it is in the `reference.json` file.
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/70e0f25b-48cb-442e-8936-e59d475f0908)

**Comment by lefouvert** [comment]
Is this correctly setted ?
![image](https://github.com/untoldwind/KontrolSystem2/assets/57873766/6d59b3b3-0591-4e65-be7b-f3ef11a1aac2)

**Comment by PhilouDS** [comment]
> @PhilouDS Is this correctly setted ?

Yes it is

**Comment by PhilouDS** [comment]
This is the settings file with the right path.
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/8ee2626b-d7ab-4697-994b-a4e653a6b803)

But the path is wrong here :( I don't know how to change this and if it's doing something.
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/9da08a24-16e3-4f0a-8f2a-78769de3a0f1)

**Comment by lefouvert** [comment]
It's default values, I don't think it's revelant.

**Comment by PhilouDS** [comment]
Sorry, all is working. I updated Kontrol System with the last version!

**Comment by untoldwind** [comment]
I think the '\\' is correct in this case. VSCode stores the config in json and inside a json-string a '\' has to be encoded as '\\'.
