### ISSUE TITLE
Generate PDF version of documentation for ChatGPT

### ISSUE THREAD

**Issue by MoreTore** [untoldwind/KontrolSystem2#147]
Would be useful to have a pdf version of the docs so that we can provide the docs to chatgpt to write scripts for us.

**Comment by untoldwind** [comment]
Actually very easy, just had to be turned on: https://readthedocs.org/projects/kontrolsystem2/downloads/
... and does not even look half as bad.

**Comment by untoldwind** [comment]
Not sure if it is helpful for this purpose, but there is also this:
https://github.com/untoldwind/KontrolSystem2/blob/master/Tools/vscode/to2-syntax/server/src/reference/reference.json

Which contains all the information of the "reference" section in a machine readable way.

**Comment by MoreTore** [comment]
Cool I created this GPT and it seems pretty good. It at least gets the syntax right and can use the functions and search the docs.

https://chat.openai.com/g/g-1XLTpfjxg-kerbal-space-program-kontrolsystems2-writer

**Comment by MoreTore** [comment]
> Not sure if it is helpful for this purpose, but there is also this:
> https://github.com/untoldwind/KontrolSystem2/blob/master/Tools/vscode/to2-syntax/server/src/reference/reference.json
> 
> Which contains all the information of the "reference" section in a machine readable way.

I think it would be possible to use the reference with a GPT action to check the syntax. Not sure exactly the best way to provide feedback to gpt tho. Maybe try to compile the code and just report the errors.

**Comment by untoldwind** [comment]
I have not looked into (the OpenAI) GPT actions yet, but if they have support for javascript/typescript, there is this:
https://github.com/untoldwind/KontrolSystem2/blob/8437adeb5bad4c845ddc6999af4069c619d47e6c/Tools/vscode/to2-syntax/server/src/to2/parser-module.ts#L225
which creates a parser https://github.com/untoldwind/KontrolSystem2/blob/8437adeb5bad4c845ddc6999af4069c619d47e6c/Tools/vscode/to2-syntax/server/src/parser/index.ts#L109
for a to2 file. (The DocumentUri is somewhat specific to vscode, but could just be left blank if just the syntax should be checked)

I guess with some minor adjustments this could be converted into a validator for reinforced learning.

**Comment by MoreTore** [comment]
> > Cool I created this GPT and it seems pretty good. It at least gets the syntax mostly right and can use the functions and search the docs.
> > 
> > https://chat.openai.com/g/g-1XLTpfjxg-kerbal-space-program-kontrolsystems2-writer
> 
> Unfortunately, I can't access this because I use the free version of chat GPT. I'm curious: is it easy to create this GPT from the doc? How does it work?

Yea it's easy to make you just gotta fiddle with the instructions for an hour to get the type of responses your looking for. You basically just provide it with the pdf and some code examples in its "Knowledge" and give it instructions like:

If a user asks you to implement some control system in the game, you should provide a high level overview of the plan. Then read the documentation to understand the standard existing functions and syntax that is available with KontrolSystems2 mod. Then you will provide code that will satisfy the users request if possible.

> After writing a code implementation, you should check  your knowledge again to fill in any placeholder values you may have used that you were unsure of initially.
