### ISSUE TITLE
Enhancement for UI

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#151]
Hi,

I have this simple UI to select a script from all available processes. Is it possible to add a sort of Scroller list to UI? For now, I'm using a slider but I thought that scroll list could be better.
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/78418444-4c74-4ba6-ba29-86e18317ac19)

**Comment by untoldwind** [comment]
The 0.5.7.6 release now has a `.add_vertical_scroll(width, height)` method (width and height are the minimum size of the scroll container, otherwise I is similar to a regular vertical layout). Currently only vertical scroll is possible (mostly because I forgot to create assets for a horizonal scollbar).

**Comment by PhilouDS** [comment]
Thanks! I'll show you the new UI as soon as I restart KSP2.

**Comment by untoldwind** [comment]
Pre-release 0.5.7.7 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.7.6)
Has a `ui_container.add_dropdown(options: string[])` method, that should realize that:

Example:
```
use { Vessel } from ksp::vessel
use { CONSOLE } from ksp::console
use { open_window, open_centered_window, screen_size, Align } from ksp::ui
use { wait_until, yield } from ksp::game

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
    CONSOLE.clear()

    const dialog = open_centered_window("Monitor", 0, 0)

    const dropdown = dialog.add_dropdown((1..20).map(fn(i) -> $"Option {i}"))

    dropdown.on_change(fn(i) -> {
        CONSOLE.print_line($"Selected {i}")
    })

    wait_until(fn() -> dialog.is_closed)
}
```
The graphics still might need some tweaking, creating a dropdown requires a loot of interconnected game-objects, so there are probably some quirks I have not noticed yet.

**Comment by PhilouDS** [comment]
Thanks! I'll have a look at this in the next days!

**Comment by PhilouDS** [comment]
@untoldwind Thanks to you I have a new Boot UI :)
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/bf4da57b-0278-4925-bc18-10bd76115ccb)

The harder part was to save the parameter values if they are changed. That's the purpose of my validate button.
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/4a6ebb27-c5a9-4d8b-94bd-b22074911b35)

Once the parameters are validated by the user, the field are disabled. You can click and the BACK button to change again the parameters or the Start button to... run the script 🥳 
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/ffd333e7-1365-4ef7-8798-9871d9ed3c9f)

**Comment by PhilouDS** [comment]
This was a lot of wok to do what Kontrol System already do 😅 The difference is that my list of missions is organised in the reverse order. So, the last mission is on the top of the list.

**Comment by untoldwind** [comment]
I slightly adjusted the positioning of the inner elements in 0.5.7.8: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.7.8

It should remove some of the pixel-atrifacts

**Comment by PhilouDS** [comment]
With version 0.5.7.8:
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/89d0f132-cac0-4ed9-bf59-7d1615a660f8)
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/40e3aa02-1add-465a-88fa-f841ee2b5db4)

**Comment by PhilouDS** [comment]
Is there any variable that returns the actual version of Kontrol System? I'd like to add this version number at the bottom of my UIs... If I can do that automatically, it would be great.

**Comment by untoldwind** [comment]
In the 0.5.7.9 release I added a `version` field to the ksp::game::MAINFRAME (https://kontrolsystem2.readthedocs.io/en/latest/reference/ksp/game.html)

**Comment by PhilouDS** [comment]
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/c25d6dab-d47e-4113-a007-39181d28b728)

**Comment by PhilouDS** [comment]
I created a list with all the bodies of the game and I used it in a dropdown. Then I have this piece of code that updated different float cells:
```rust
dropdown.on_change(fn(i) -> {
  body_name.value = find_body(dropdown.options[i]).value.name
  periapsis_input.value = floor(find_body(dropdown.options[i]).value.atmosphere_depth) + 10000
  apoapsis_input.value = floor(find_body(dropdown.options[i]).value.atmosphere_depth) + 10000
  altitude_input.value = floor(find_body(dropdown.options[i]).value.atmosphere_depth) + 10000
})
```
This gives me the following error:
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/bbdc6650-99fd-42a7-abb8-ead2c6651c9c)

I can make this error disappears adding in a last line `CONSOLE.print("")`.

Is it a normal behaviour?

**Comment by untoldwind** [comment]
Yes, this is kind of a bug with type inference. The dropdown callback is probably not the only callback affected by this.

**Comment by PhilouDS** [comment]
> Yes, this is kind of a bug with type inference. The dropdown callback is probably not the only callback affected by this.

Indeed, I've already noticed that with button and field input.

**Comment by untoldwind** [comment]
This should be fixed in pre-release 0.5.8.0 (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.8.0):
The callback are tweaked to accept functions with arbitrary returns (which just gets ignored)

**Comment by PhilouDS** [comment]
Hi,

I have a new UI to select a specific vessel  among all vessels. After selecting a vessel, I can use its geocoordinates.
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/91e936ef-ec4c-4606-bde8-2c3e2a261cb2)

I want to improve the UI to let the player enter geocoordinates (after selecting a body). So the player must choose between "select a vessel", "enter geocoordinates" or "nothing".

1- I can do that with toggle buttons but is it possible to have radio buttons more suitable when only one item can be selected?

2- Until now, when I need to change from one container to an other, I have to `remove` the container and if I need it later, I must recreate it. I think it's not optimal. Is it a way to "hide" and "show" a container without destroying it each time?

**Comment by untoldwind** [comment]
Unluckily I had not much time to test this.
In the current pre-release: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.9.3
the UI elements now have a `.visible` field to toggle show/hide.
There might be some issue with layouting though

**Comment by PhilouDS** [comment]
Thanks, I'm trying this. I'm having this error message with a dropdown:
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/9a3a59c9-8451-42a3-a5da-e6c265c7032e)

```rust
const dropdown_vessels = ves_box.add_dropdown(names_of_vessels.value)
  dropdown_vessels.bind(names_of_vessels)
 ```
 `names_of_vessels` is a list of all my owned vessels' names.

How can I correct this error? How can I get a `Cell<T>`?

**Comment by PhilouDS** [comment]
The `visible` field works as expected. Thank you.
My next wish: radio button instead of toggle 😋
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/dc21783e-d22e-4a0a-8177-372684bb43b9)
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/24cf1480-885d-4db8-9b4f-9de321fadede)

**Comment by untoldwind** [comment]
The `dropdown.bind` creates a binding for the value of the dropdown (i.e. the currently selected index) not the available options to select from.
You can change the options just by setting the `dropdown.options` field. IMHO there is no need to create a special binding method for this.
