### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by versvisa** [untoldwind/KontrolSystem2#158]
Hello, I would appreciate a Discord server or other more casual place to discuss this mod. Does it exist already?

**Comment by untoldwind** [comment]
I think there was one created, but I only use discord as an occasional teamspeak replacement.
Problem is, that I already have 3 (sometimes even 4) different messengers open for work nearly all the time, adding another one is not really an option.

I think there is a modding community discord, which might be the better choice than a dedicated one.

Apart from that: It is perfectly reasonable to ask any kind of question here. On a somewhat philosophical level: An open question could be considered a bug in the documentation ... and I am horrendously bad in fixing those ;)
