### ISSUE TITLE
No information error bug

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#16]
When making a circular reference, I got an error that didn't specify where, or even which file was problematic.
The error read:
ERROR:  [(0, 0)] unknown error
Index was out of range.
Must be non-negative and less than the size of the collection.
Parameter name: index

Here's example code that generates this error

use { Vessel } from ksp::vessel

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
	
	let pitch = 1.0
	let pitch_SP = 12.0
	let pitch_actual = vessel.pitch_horizon_relative
	let delta = pitch_actual - pitch_SP
	
	if (delta < 10) {			//need hard pitching until a bit off the ground
		pitch = pitch_SP
	} else {
		pitch = pitch_incrementer(pitch_actual, pitch_SP,delta)
	}
}

pub fn pitch_incrementer(pitch_actual: float, pitch_SP: float) -> float = {
	
	10.0
}

Removing the reference to delta in calling the function fixes it:
pitch = pitch_incrementer(pitch_actual, pitch_SP,delta)
to
pitch = pitch_incrementer(pitch_actual, pitch_SP)

**Comment by untoldwind** [comment]
Should now produces an error message that `pitch_incrementer` has been called with too many arguments (3 > 2)

**Comment by untoldwind** [comment]
I am closing this for now
