### ISSUE TITLE
BUG print_at ?

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#162]
Version 0.5.8.2

Hi. The code below works perfectly fine:
```rust
while(true) {
  CONSOLE.print_at(2, 0, $"{current_time():N2}")
  yield()
}
```

But if the column variable is not 0:
```rust
while(true) {
  CONSOLE.print_at(0, 2, $"{current_time():N2}")
  yield()
}
```
then, the script runs but nothing appear in the console. No error message. Just nothing. I know the script is running because of the red square. How strange is that!
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/9939654f-011e-41b5-9577-020970e1f8cb)

**Comment by untoldwind** [comment]
Yes this is a bug ... might have happened during the introduction of the command prompt.

**Comment by untoldwind** [comment]
This should work now in 0.5.8.3

**Comment by PhilouDS** [comment]
NICE

![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/42888018-e3b5-4756-9008-1c8d0d851f05)

**Comment by PhilouDS** [comment]
> This should work now in 0.5.8.3

For me, the problem is solved. Thanks.
