### ISSUE TITLE
Request for a new part property (id)

### ISSUE THREAD

**Issue by lefouvert** [untoldwind/KontrolSystem2#165]
Hi !

I gess this one is an easy one.
Could we benefit from a new proprety on parts : id ? At least at vessel scale, but it would be better, I think, if it could be an id unic at «Universe» scale. (I mention the two possibilities since KSP2 seems to have some KSP1 legacy and I think it had thoses two kinds of id).

If you have the choice, I don't think both ids are usefull, the «Universe» scale should be enougth.

**Comment by untoldwind** [comment]
It kind of depends on the use-case: Internally there is a `GlobalId` (which is somewhat similar to a UUID, i.e. pretty much unique in the universe ... the real one ;) ) and it would be easy to just use that one.
But (there is always one): The `GlobalId` actually comes from the underlying SimulationObject, which does not exists in the OAB, in that case there result is pretty much random.

So: Should be part id be stable in the OAB and correlate to the part id of the realized vessel?

In that case: It should be possible to generate a synthetic id based on where in the part appears in the part-hierarchy of the vessel.

**Comment by lefouvert** [comment]
Ah crap ! I Always forget about OAB ! Ofc, it would be logical than an inflight feature of this kind be available in OAB and expected that the value don't change between VAB and launchpad, even if I don't see any usecase.
... It is ? What happen if you load 3 times the same vessel and launch it ? Wouldn't it have sense than OAB part id and inflight UUID don't match since OAB parts don't really exists ?

I think there is no need both ids match since the existence of this id in OAB allow some precalculation but as a vessel can be virtualy infinitly reloaded with and without launch, UUID don't make sense in OAB. But as I never use OAB processus, maybe I'm not the most objective one.

**Comment by untoldwind** [comment]
Yes, if a vessel is loaded three times then the `GlobalId`s should be different for each of them.
Through I was not precise in my wording, the problem in the OAB is, that internally there is a "if SimulationObject does not exists then new GlobalId" logic, i.e. in the OAB the `GlobalId` would change with each call, which would lead to pretty unpredictable results.
In short: That one is pretty much useless in the OAB context

**Comment by lefouvert** [comment]
My english, and the writen media didn't allow me to exactly say what I mean. A few theatrical facial expressions, voice inflections and greater ease in language would have made it clearer.
Unic Id for each part launched : I got it (it is what I expect :) Even better If it's at True Real Universe Of The Palpables Things scale. TRUOTPTUID is a bit long acronym, isn't it ?)
I was only grinding my gears about OAB parts concept. I think if at 1 vessel load scale, part id is consistent, it is enought to precompute things if needed, but I don't see any purpose this id to be consistent at larger scale.

**Comment by untoldwind** [comment]
In 0.5.8.4 the `ksp::vessel::Part` now has an `id` property based on the `GlobalId`.
As discussed this is (current?) not available in the OAB
