### ISSUE TITLE
Control multiple vessels simultaneously

### ISSUE THREAD

**Issue by versvisa** [untoldwind/KontrolSystem2#166]
Starting a program on one vessel, then switching to a second vessel to run a second instance does not seem to work well. The first vessel goes out of control. Could this be implemented/test/documented? I am not sure what the current state or expected behavior is.

**Comment by untoldwind** [comment]
I do not think the game (currently?) supports this. When switching the active vessel the input controls are moved to the new vessel (naturally), during that the autopilots also get un-hooked ... or at least partly un-hooked.
