### ISSUE TITLE
Increase reboot timeout?

### ISSUE THREAD

**Issue by frogfromlake** [untoldwind/KontrolSystem2#168]
Hey man :)
Thanks for your updates :) didnt find the time yet to help with docu #140 because i also have a lot of work to do on my job but i'll keep it in mind.

My question: **is there a way to increase the reboot timeout?** My script can not be build within the timeout because its a bit excessive i guess. But before i throw out everything and just write a flight routine i wanted to check first if increasing the timeout would be an option.

im running 6 processes but this should not be the problem. My telemetry process seemed to reached some kind of limit since the reboot time increased from kind of normal to timeout.

**Comment by untoldwind** [comment]
I will make this a configuration parameter.
Though: The standard timeout should be 30s ... I though this would be plenty. There is a possibility that something in the compiler goes haywire

**Comment by untoldwind** [comment]
Version 0.5.8.5 should now have a timeout section in the mod settings (default is still 30s).

**Comment by frogfromlake** [comment]
> Version 0.5.8.5 should now have a timeout section in the mod settings (default is still 30s).

Very nice man, thanks. Good job.

**Comment by lefouvert** [comment]
> I will make this a configuration parameter.
Though: The standard timeout should be 30s ... I though this would be plenty. There is a possibility that something in the compiler goes haywire

I'm at 22 seconds compilation time, and I've not done a quarter I expect to do with this mod :)

**Comment by untoldwind** [comment]
In the 0.5.9.0 pre-release (https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.9.0) I increased the log-level a bit. Can you check the `BepInEx/LogOutput.log` file after a reboot, it should contain something like this:
```
[Info   :KontrolSystem2] Add Directory: Z:\home\bjunglas\.local\share\Steam\steamapps\common\Kerbal Space Program 2\BepInEx\plugins\KontrolSystem2\to2Local
[Info   :KontrolSystem2] Phase1: 00:00:00.1232732
[Info   :KontrolSystem2] Phase2: 00:00:00.1236979
[Info   :KontrolSystem2] Phase3: 00:00:00.1272427
[Info   :KontrolSystem2] Phase4: 00:00:00.1276126
[Info   :KontrolSystem2] Phase5: 00:00:00.1314226
[Info   :KontrolSystem2] Phase6: 00:00:00.1319791
[Info   :KontrolSystem2] Phase6: 00:00:00.1322367
[Info   :KontrolSystem2] Phase7: 00:00:00.1323146
[Info   :KontrolSystem2] Finalized: 00:00:00.5348516
```
This should help a bit in narrowing down where optimization should take place.
