### ISSUE TITLE
Lack of Units in Documentation

### ISSUE THREAD

**Issue by lehrmanaidins** [untoldwind/KontrolSystem2#169]
I am assuming that the returned values for certain functions and fields are in SI units; however, it would save a lot of testing every time if, in the documentation, it specifically defined what unit the returned value is represented as (i.e. m, m/s, kg, kN, etc.).

**Comment by PhilouDS** [comment]
For what I know, the units are the same than the units in the game.
Time : s
Velocity : m/s
Acceleration : m/s²
Distance : m
Mass : metric tons
Thrust : kN

**Comment by untoldwind** [comment]
To my knowledge the game does everything in SI units internally, so @PhilouDS list should cover 99% of all the cases.
To be sure though I would have to look recheck in the game UI how each value is displayed.
