### ISSUE TITLE
Pass Command Line Arguments to Scripts

### ISSUE THREAD

**Issue by kbleeke** [untoldwind/KontrolSystem2#17]
For me, each script basically has a couple as constants that effectively are the inputs to the script. For example, the ascent script takes the desired apoapsis and inclination as inputs. A "fine-tune closest approach" takes the desired distance to the target. An "arguments" feature would save us from having to edit common scripts every time.

A simple idea would be to basically implement command line arguments for scripts. Then the script can check the arguments and possible override its inputs with custom values. 

I image this needs at least two things
- The script needs to be able to access the arguments
- Set Command Line arguments in the UI

I'd give it a shot on implementing this, if it is a good idea. I'd like some guidance on what the UI could be (a button that opens a modal window?).

**Comment by untoldwind** [comment]
Well in the `KontrolModuleExtensions.cs` `getEntryPoints` there already is some logic to inspect the arguments of the `main_` function. I.e. the `vessel: Vessel` parameter of `main_flight` is optional.

It should be possible to extend this, and convert the `Entrypoint` delegate to a struct with additional information.

The only problem I see are potentially default values. In your example you would porbably like to write
```
pub fn main_flight(vessel: Vessel, distance: float = 1000) -> Result<Unit, string> = {
```
(or something like that)

The language itself allows this, but the `1000` would be an expression that needs to be evaluated to show in the UI.

A completely different solution for the problem of user input would be to have a `ksp::ui` module with a `modal_dialog` function. This would also add the possibility to have different kind of widgets, min/max for values and so on.

**Comment by kbleeke** [comment]
Ok, I submitted a small follow-up with some docs.

I think what I'd still like to do is making the arguments somewhat persistent. Currently, they disappear if you close the window or open another arguments window.

I guess, they could be stored in the Process class. As far as I understand, that would survive until the next reboot. Is there anything that lives longer than that?

**Comment by untoldwind** [comment]
The processes list is rebuild on reboot to handle the cases of script added/removed and so on.
But of course in the `Mainframe.DoReboot` one could cache the previous argument values in a Dictionary and then patch the new processes list.

Alternatively all the changed argument values could be stored in a complete separate Dictionary in the Mainframe (process.Name should be stable enough as key)

**Comment by untoldwind** [comment]
I think this can be closed for now, as the basic functionality is quite stable now.
Further improvements should probably get their own tickets.
