### ISSUE TITLE
Uncertain future of KSP2

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#171]
Hello @untoldwind 

Did you hear about the last KSP news and the uncertain development of KSP2?

Whatever happens, I'm still playing with KSP2 and Kontrol System. I'd like to land and drive a Rover on the surface of Duna :)

**Comment by untoldwind** [comment]
I just read the news this morning.
The most pragmatic solution seems to be: Wait and observe ;)

As for this mod though: I will continue support it as long as the game still exists.

**Comment by PhilouDS** [comment]
> I just read the news this morning. The most pragmatic solution seems to be: Wait and observe ;)
> 
> As for this mod though: I will continue support it as long as the game still exists.

Great! Thank you :)

**Comment by lefouvert** [comment]
Heard about last night. Sad. Had high expectation for this game. They dropped to «don't expected more than current state», but as said by Untoldwinds, best to do is wait and see.
