### ISSUE TITLE
vessel.name

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#174]
Hello,

Is it possible to change the field `name` to writable instead of read-only? Thanks :)

**Comment by untoldwind** [comment]
Added this to the pre-release: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.9.2
(Seems to work as intended, but might need a bit more testing)

**Comment by PhilouDS** [comment]
> Added this to the pre-release: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.9.2 (Seems to work as intended, but might need a bit more testing)

Thanks, it seems to work indeed.
Good to know: the name displayed is updated when you change the view (after switching to map view for example)
![image](https://github.com/untoldwind/KontrolSystem2/assets/77538240/c0496a84-0ea0-4010-90f4-ae9391fe795f)
