### ISSUE TITLE
Choose a specific vessel at target

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#176]
Is it already possible to have access to the list of all the vessels in the game (orbiting, landed or splashed)? And I guess this includes the debris (I don't know if the game considers debris as vessels).

This could be interesting to rendezvous with one specific vessel. For example:
```
vessel.target = list_of_all_vessels.find(fn(V) -> V.name == "ISS")
```

**Comment by untoldwind** [comment]
There is the `ksp::vessel::get_vessels_in_range()` and `ksp::vessel::get_all_owned_vessels()` functions.
The former is something the game provides, though I am not entirely sure what "in-range" means exactly.
