### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by PhilouDS** [untoldwind/KontrolSystem2#178]
Hello @untoldwind 

I hope you're going well.

I installed the new KSP2 update and, when I try my maneuver script to create a maneuver node, I have this error:
![20240611214421_1](https://github.com/untoldwind/KontrolSystem2/assets/77538240/c9d55cc1-3bb1-4968-94c2-de5313a4f6f4)

The problem comes from `ship.maneuver.add(current_time() + 500, 0, 0, 0)`

**Comment by untoldwind** [comment]
This is somewhat surprising, the above method still exists. Maybe it is some wired assembly-version mismatch. I just recompiled everything base on the new libraries and it works for me.
Please check if 0.5.9.4 fixes the problem for you as well: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.5.9.4

**Comment by untoldwind** [comment]
Pushed it to SpaceDock as well.
... the pre-release was dangling around for too long anyway ;)
