### ISSUE TITLE
Methane engine modes

### ISSUE THREAD

**Issue by tbma2014us** [untoldwind/KontrolSystem2#179]
Hello @untoldwind

I hope you're doing well. 

I am working on a space plane autopilot, which works reasonably well for lift-off. 

But now I am switched to landings and noticed that I cannot do engine cycle switching.

Would it be possible to add bindings to switch methane engine cycles and reverse trust in some types?

**Comment by untoldwind** [comment]
I have not done many tests with that, but changing the mode of the engine should be possible with this method:
https://kontrolsystem2.readthedocs.io/en/latest/reference/ksp/vessel.html#change-mode
where the names of the modes could be extracted from the `engine_modes` property.

Alternatively:
You could try defining custom action groups for the vessel and trigger them with e.g.:
`vessel.actions.custom1 = true`

**Comment by tbma2014us** [comment]
Thanks a lot! I’ll give that a try!

**Comment by tbma2014us** [comment]
@untoldwind I was thinking about custom groups, but that creates a pre-requisite dependency.
 
Right now I am testing it like this, and getting just "Engine" instead of engine mode.

`fn current_engines(vessel: Vessel) -> ksp::vessel::ModuleEngine[] = {
    let current_engines:  ksp::vessel::ModuleEngine[] = []
    for(_engine in vessel.staging.parts_in_stage(vessel.staging.current)) {
        if(_engine.is_engine) {
            CONSOLE.print_line($"Engine: {_engine.engine_module.value.part_name} Mode:{_engine.engine_module.value.current_engine_mode.name}")
            current_engines += _engine.engine_module.value
        }
    }
    current_engines
}
`

Engine: engine_3v_hydrogen_swerv Mode:Engine
Engine: engine_1v_turboramjet_methane_whiplash Mode:Engine
Engine: engine_1v_turboramjet_methane_whiplash Mode:Engine
Engine: engine_1v_turboramjet_methane_whiplash Mode:Engine
Engine: engine_1v_turboramjet_methane_whiplash Mode:Engine
Engine: engine_1v_turboramjet_methane_whiplash Mode:Engine
Engine: engine_1v_turboramjet_methane_whiplash Mode:Engine

**Comment by tbma2014us** [comment]
@untoldwind I was thinking about action groups, but that creates a prerequisite.

I am testing it like this, and the results are positive. For engines without mode switching, it just returns "Engine."
```
fn current_engines(vessel: Vessel) -> ksp::vessel::ModuleEngine[] = {
    let current_engines:  ksp::vessel::ModuleEngine[] = []
    let engine_parts = vessel.staging.parts_in_stage(vessel.staging.current).filter(fn(e) -> e.is_engine)
    for (_part in engine_parts) {
        CONSOLE.print_line($"Engine: {_part.engine_module.value.part_name} Mode:{_part.engine_module.value.current_engine_mode.name}")
        current_engines += _part.engine_module.value       
    }
    current_engines
}
```
Engine: engine_1v_methane-methalox_rapier Mode:Air Breathing
Engine: engine_1v_methane-methalox_rapier Mode:Air Breathing
Engine: engine_1v_methane-methalox_rapier Mode:Closed Cycle
Engine: engine_1v_methane-methalox_rapier Mode:Closed Cycle
Engine: engine_1v_methane-methalox_rapier Mode:Air Breathing

**Comment by untoldwind** [comment]
Inside the game the EngineMode is a quite complex structure and not just a fixed enum. I guess the long-term plan was to have many kinds of engine each with their own set of modes (like switching a hypothetical Hall-Effect engine from Xenon to Argon ... or something).

To get the full list you could additionally iterate through the `.engine_modes` properties in addition to the `.current_engine_mode`

**Comment by tbma2014us** [comment]
Yes. I am doing it like this now, and it works as intended—that is, it does not trigger unnecessary stages.

1st, I am enumerating the engines in the current stage and then switching them to the desired cycle if they are capable.
```
        if(open_cycle.value){
                for(engine_ in current_engines(vessel)) {
                    if(engine_.engine_modes.find(fn(m) -> m.name == "Closed Cycle").defined) {
                        log("Engine in closed cycle")
                        engine_.change_mode("Closed Cycle")
                    }
                }
                open_cycle.value = false
            }
```

 I am continuing my testing.

**Comment by tbma2014us** [comment]
Thank you! It is working, and I consider the issue closed.
