### ISSUE TITLE
Documentation request on usage of throttle and steering managers?

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#18]
I'm stumped on how to steer the craft besides vessel.autopilot.target_orientation.  I would like to pass direction (since I want roll to remain at 0 with respect to the horizon) with planes.

I can't get the throttle manger to do anything.  I  don't know the functions of vessel.throttle_manager, vessel.set_throttle, vessel.set_throttle_provider.  I don't know what an fn(float) is.

**Comment by untoldwind** [comment]
The `throttle_manager` is in a somewhat usable stage, the rest of them probably need some mayor adjustments (I just C&P them from KSP1).

**Comment by EloxZ** [comment]
Check this one

https://github.com/untoldwind/KontrolSystem2/blob/8d79e72485f792df001b07b22b087a532f3eb1f3/KSP2Runtime/to2/flightinput_example.to2#L5

Although you can be more precise going slow

**Comment by untoldwind** [comment]
I documented the different ways to control the vessel here: https://kontrolsystem2.readthedocs.io/en/latest/interact/control.html

The `SteeringManager` is now just controlling the raw pitch, yaw, roll values. 
I will migrate the old (way more complex) steering manager at a later date, there are just to many things that do not add up correctly (literally ;) ), and the parameters for the PID-loops highly depend if you tweaked the physics engine or not (i.e. wibble-wobblyness of all the things).
I really hope that the upcoming patch will address these issues, then I give it another try.

**Comment by untoldwind** [comment]
Closing this for now to keep list of issues managable. Reopen if there are still unclarities
