### ISSUE TITLE
Roll weirdness bug

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#23]
Results from roll_horizon_relative is inconsistent, or I don't understand the output.

When the craft is level with the horizon, roll_horizon_relative returns the same result as pitch_horizon_relative
When rolling left or right, when pointed above the horizon, roll returns a positive number (sometimes will switch negative if rolled >45° or yaw across 90°)
When pitched below the horizon, roll returns a negative number

For example, if I'm 1 degree above the horizon, and even with the horizon, roll_horizon_relative will return 1.0.  If I bank to the left 20°, roll_horizon_relative will return 20.0.  If I bank to the right 20°, roll_horizon_relative will return 20.0.  I would expect one of these to be -20.0, but both are positive.

While maintaining that angle, if I dip my nose below the horizon, it returns -20° either way I'm banked.

Test with this code:

use { Vessel } from ksp::vessel
use { CONSOLE } from ksp::console
use { sleep } from ksp::game
pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
    CONSOLE.clear()
	while (true) {
		sleep(0.05)
		CONSOLE.print_at(1,0,"Roll relative to horizon: " + vessel.roll_horizon_relative.to_fixed(2)+"   ")
		CONSOLE.print_at(2,0,"Pitch relative to horizon: " + vessel.pitch_horizon_relative.to_fixed(2)+"   ")
	}
}

**Comment by untoldwind** [comment]
I took those directly from the telemetry data of the vessel. I'll look into it once (if? ... crossing fingers) the upcoming patch lands.
Maybe it magically gets fixed by itself ;)

**Comment by SodaPopinski** [comment]
> I took those values directly from the telemetry data of the vessel (i.e. no calculation on my side). I'll look into it once (if? ... crossing fingers) the upcoming patch lands. Maybe it magically gets fixed by itself ;)

I vaguely recall kOS/KSP1 pitch and roll values were weird,  and counterintuitive.  I can't find the explanation on it right now, but I believe they didn't directly related to the NavBall.  I'm pretty sure I had to use vector math to get pitch using forevector and up vector, and starvector to get roll.

**Comment by untoldwind** [comment]
If you have a working formula I can use that instead of the telemetry data.

**Comment by untoldwind** [comment]
It is really hard to understand what is going on internally, there are so many different frames of references going around.

Here is what might be helpful in the meantime (all vectors are in the non-rotating coordinate system of the main body)
* `vessel.facing` should represent the rotation of the vessel as seen from the control frame (which is different for rockets and planes).
  * That is `vessel.facing.vector` should point in the forward direction
  * `vessel.facing.up_vector` should be the up vector of the vessel (i.e. up for a plane)
  * `vessel.facing.right_vector` should be the right vector of the vessel
* `vessel.up`, `vessel.north`, `vessel.east` should be vectors of the horizon
* So `atan2_deg(vessel.east * vessel.facing.vector, vessel.north * vessel.facting.vector) should be the Heading

... and then it becomes a hazzle to untangle the roll and pitch. Sorry I looked to last half an hour at too many quaternions, my brain is mush right now.

**Comment by SodaPopinski** [comment]
> It is really hard to understand what is going on internally, there are so many different frames of references going around.
> 
> Here is what might be helpful in the meantime (all vectors are in the non-rotating coordinate system of the main body)
> 
> * `vessel.facing` should represent the rotation of the vessel as seen from the control frame (which is different for rockets and planes).
>   
>   * That is `vessel.facing.vector` should point in the forward direction
>   * `vessel.facing.up_vector` should be the up vector of the vessel (i.e. up for a plane)
>   * `vessel.facing.right_vector` should be the right vector of the vessel
> * `vessel.up`, `vessel.north`, `vessel.east` should be vectors of the horizon
> * So `atan2_deg(vessel.east * vessel.facing.vector, vessel.north * vessel.facting.vector) should be the Heading
> 
> ... and then it becomes a hazzle to untangle the roll and pitch. Sorry I looked to last half an hour at too many quaternions, my brain is mush right now.

No worries!  You've got a lot on your plate, especially with the recent update.

Anyway, I'm not sure I was doing it right, but it was close enough for me.

This is the code I used in kOS.  Now that I know the equivalent vectors in KS2, it's seems easy enough to do the same thing.

function getpitch {		//get vehicle pitch
	return (90-vectorangle(up:vector,facing:forevector)).
}

function getRoll {
	return (90 - vectorangle(up:vector, ship:starvector)). 
}

Heading seems a bit more complicated.  Apparently, I wrote a separate heading function for rockets when they were pitched up past 45 degrees.  For some reason, in kOS, I got heading from ship:bearing. I suspect ship:heading was specific for heading towards a target or something.

**Comment by SodaPopinski** [comment]
Here's the KS2 version.  It only gives you between +/- 90°.  You can work out an additional check to get the vector angle between vessel.up and vessel.facing.up_vector to determine if they're further than 90°, then add or subtract the difference between the current output and 90° or -90°


pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
	CONSOLE.clear()
	while (true) {
		sleep(0.05)
		CONSOLE.print_at(0,0,"Roll: " + (90 - acos_deg(vessel.up.dot(vessel.facing.right_vector) / (vessel.up.magnitude * vessel.facing.right_vector.magnitude))).to_fixed(2))
	}
}

**Comment by SodaPopinski** [comment]
Here's a version that handles being inverted

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
	CONSOLE.clear()
	while (true) {
		sleep(0.05)
		
		let roll = (90 - acos_deg(vessel.up.dot(vessel.facing.right_vector) / (vessel.up.magnitude * vessel.facing.right_vector.magnitude)))
		let up_angles = (acos_deg(vessel.up.dot(vessel.facing.up_vector) / (vessel.up.magnitude * vessel.facing.right_vector.magnitude)))
		if (up_angles > 90) {
			roll = 180-roll
		}
		if (roll > 180) {
			roll = roll-360
		}
		CONSOLE.print_at(0,0,"Roll: " + roll.to_fixed(2))
	}
}

**Comment by untoldwind** [comment]
Thanks for working that out. I used that for a new [`vessel.pitch_yaw_roll`](https://kontrolsystem2.readthedocs.io/en/latest/reference/ksp/vessel.html#id32) field on the vessel.

The value matched quiet well with the navball as far as I was able to test.

**Comment by untoldwind** [comment]
Will close this for now. Reopen if the issues rolls back.
... ok my puns could be better
