### ISSUE TITLE
Error when running launch_rocket

### ISSUE THREAD

**Issue by ThunderousEcho** [untoldwind/KontrolSystem2#3]
Replication:
On v0.1.4 of KontrolSystem2, load Kerbal K1 (a stock vessel) on the launchpad. Run launch_rocket.
Also happens with hello_world_flight and exec_node.

![image](https://user-images.githubusercontent.com/10161961/224465535-436310f3-b62a-4e63-943e-4fafd8e3e729.png)

BepInEx log which appears to have the NullReferenceExceptions
[LogOutput.log](https://github.com/untoldwind/KontrolSystem2/files/10947635/LogOutput.log)

KSP2 log
[Ksp2.log](https://github.com/untoldwind/KontrolSystem2/files/10947640/Ksp2.log)

Also, are you accepting pull requests? Is there anything that I could do for you on this project?

**Comment by ThunderousEcho** [comment]
BepInEx log which appears to have the NullReferenceExceptions
[LogOutput.log](https://github.com/untoldwind/KontrolSystem2/files/10947635/LogOutput.log)

**Comment by untoldwind** [comment]
Yes ... I really should have tested the stock vessels, shouldn't I ;)

Anyways thanks for the feedback and the attached logs, that really helped. I do not think that this is really related to the vessel, but rather one of those pesky timing issues (have not figured out how exactly it is supposed to work, but there certainly is a state where the internal VesselComponent does not have a VesselAutopilot.

I reworked that part and used the more official looking methods (with null-value checks). Maybe you can checkout the pre-release https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.1.4.1 as these kind of things are really hard to narrow down and reproduce.

As for "Kerbal K1": The launch script still did not work as it was to zealous with staging (i.e. I did not considered the case of a partial flameout). I think I fixed that as well. BTW: These are the kind of issues I really like to tinker with.

And finally:
I gladly accept and appreciate any kind of PR and would love to see more developers getting involved, there are so many things that can be improved upon.

I probably should add something of a more structured laundry list, but out of the blue:
* More bindings for game related stuff (mostly vessel part related things, like solar panels, fairing, dock modules etc)
* Adding support for RCS steering (... and actually figure out how RCS can be activated/deactivated in the first place ;) )
* Scripts to create maneuvering nodes with a SOI change (e.g. get an Kerbin exit trajectory to Duna)
* UI improvements
  * Be able to scroll up the console history somehow
  * Better display of error messages (... maybe show the code sniplet that is not compiling)
  * Maybe a rudimentary ingame editor for scripts
  * Have something like a REPL mode like the original kOS had

... I can just go on like this. I will put together a document in the Contributing section of the documentation

**Comment by EloxZ** [comment]
I would like to contribute too, but I don't want to step on someone else's code/decisions so it will be nice if we open issues.

**Comment by ThunderousEcho** [comment]
@untoldwind I tested the prerelease and it worked, thanks.
