### ISSUE TITLE
IL Module Terminated error

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#32]
I get an error that says:
IL Module Terminated with error:
Invalid IL code in IL_CHECK/AsyncFunction_main_fli

It seems to be a problem when I pass a value from a function to print with the CONSOLE.  Happens with either print_line or print_at

Example code
pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
		let roll = getFloat(vessel)
		CONSOLE.print_line(roll.to_string())
		CONSOLE.print_line(getFloat(vessel).to_string())
}

fn getFloat(vessel: Vessel) -> float = {
	90.0
}

If you comment out the second print command, it works fine.

**Comment by untoldwind** [comment]
That was a tricky one:
* Moving `.to_string()` to `getFloat()`  works
* Making `getFloat()` a `sync` function` works

Problem was actually: Result of `getFloat()` is async, but `.to_string()` is sync, so `CONSOLE.print_line(` was operating as if `getFloat().to_string()` was sync.

**Comment by untoldwind** [comment]
Should be fixed in 0.1.9.3

**Comment by untoldwind** [comment]
Closing this for now. Reopen if the issue still persists
