### ISSUE TITLE
Current dynamic pressure

### ISSUE THREAD

**Issue by dboehmisch** [untoldwind/KontrolSystem2#34]
Possible to get the current dynamic pressure?

Right now I'm doing it like this:
> let Q : float = 0.5 * vessel.atmosphere_density * vessel.surface_velocity.magnitude * vessel.surface_velocity.magnitude

This was in kOS as SHIP:Q -- [https://ksp-kos.github.io/KOS/structures/vessels/vessel.html#attribute:VESSEL:Q](https://ksp-kos.github.io/KOS/structures/vessels/vessel.html#attribute:VESSEL:Q)

Source for Q calc: [https://www.eol.ucar.edu/instruments/dynamic-pressure](https://www.eol.ucar.edu/instruments/dynamic-pressure)
> "The dynamic pressure is equal to 0.5 times the air density times the airspeed squared, so dynamic pressure can be used to determine the airspeed of the aircraft."

**Comment by untoldwind** [comment]
In the 0.2.0 pre-release: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.2.0
I added:
* `vessel.static_pressure_kpa` (in kPa)
* `vessel.dynamic_pressure_kpa` (in kPa)
* `vessel.sound_speed` (m/s I suppose)
* `vessel.mach_number`

Hope that helps

**Comment by untoldwind** [comment]
Closing this for now. Reopen if there is still missing telemetry data.
