### ISSUE TITLE
Time to apoapsis

### ISSUE THREAD

**Issue by dboehmisch** [untoldwind/KontrolSystem2#35]
Possible to get the current time to apoapsis? (and PE)

This was exposed in kOS as SHIP:OBT:ETA:APOAPSIS, or just ETA:APOAPSIS -- [https://ksp-kos.github.io/KOS/structures/orbits/eta.html](https://ksp-kos.github.io/KOS/structures/orbits/eta.html)

**Comment by SodaPopinski** [comment]
Looking at maneuvers.to2, I believe it's: orbit.next_apoapsis_time()

**Comment by dboehmisch** [comment]
> Looking at maneuvers.to2, I believe it's: orbit.next_apoapsis_time()

It seems you're correct, but the return values are a float and a string (unlike for the reciprocal function for the PE which is only a float). I'm not familiar enough with the underlying language/syntax to understand how to assign the return values to variables. Doing this:
> let (AP, AP_str) = vessel.orbit.next_apoapsis_time()
Gives me this error:
> InvalidType: Expected right side to be a tuple or record, but got Result <float, string>

I've tried some different permutations that I can find on StackOverflow for C#, but I can't seem to make it work. Thoughts?

**Comment by dboehmisch** [comment]
In the meantime, I've figured out a workaround:
> (vessel.orbit.next_periapsis_time()-current_time()) - (vessel.orbit.period / 2)

**Comment by untoldwind** [comment]
The return of `orbit.next_apoapsis_time()` is a [Result<float, string>](https://kontrolsystem2.readthedocs.io/en/latest/language/special_types/result.html) (see the section how to access the value).

The reason is, that for hyperbolic orbits there is simply no such time and just get an error message instead of a value. If you are certain that you are only dealing with elliptic orbits you can just write
```
orbit.next_apoapsis_time().value
```

**Comment by untoldwind** [comment]
Now that I think about this: Maybe this should be just an `Option<float>` instead?

**Comment by dboehmisch** [comment]
Excellent, thank you! Untold, you’re doing great work with this project. I really appreciate that there is something so functional already for KSP2. —Daniel BoehmischOn Mar 19, 2023, at 7:55 AM, Bodo Junglas ***@***.***> wrote:﻿
The return of orbit.next_apoapsis_time() is a Result<float, string> (see the section how to access the value).
The reason is, that for hyperbolic orbits there is simply no such time and just get an error message instead of a value. If you are certain that you are only dealing with elliptic orbits you can just write
orbit.next_apoapsis_time().value

**Comment by dboehmisch** [comment]
To give some feedback to your question, it seems inconsistent that the AP and PE calls have different return values. However you decide is best, please consider making it the same for both functions and adding the link you provided to me about the Result handling to the documentation for both.

**Comment by untoldwind** [comment]
Yes, I was wondering about this inconsistency as well.
In most of the implementations of Kepler orbits (and there are a lot out there ;) ), I have seen something like this:
```
AP(radius) = (1 + eccentricity) * semiMajorAxis
PE(radius) = (1 - eccentricity) * semiMajorAxis
```
In case of a hyperbolic orbit `semiMajorAxis` is negative by convention (e.g. https://en.wikipedia.org/wiki/Hyperbolic_trajectory), so `PE` is still positive (eccentricity > 1). `AE` would be negative and of no particular value for anything ... though it is still a finite number and not NaN or Infinity.

Though call actually ;)

**Comment by untoldwind** [comment]
The API in the 0.2.1 should be consistent now, in the sense that everything apoasis releated is an Option

**Comment by untoldwind** [comment]
I'm closing this for now as there have not been any major complaints about the change ;)
