### ISSUE TITLE
How to get surface vectors UP and Progade?

### ISSUE THREAD

**Issue by kbleeke** [untoldwind/KontrolSystem2#4]
Hi, this could either be a questions or a bug report, depending on how wrong I am :)

I haven't done any programming KSP so far until I stumbled upon this today. I didn't know how to do anything, so I thought, why try to launch a rocket with https://github.com/TheGreatFez/Ascent_Evolution ? Anyways, to the point.

I'm trying to calculate the pitch angle in a gravity turn (tag GT2.0 in the repo). This is calculated from the angle between the UP vector and surface prograde. `set pitch_ang to 90 - VANG(UP:vector,srfprograde:vector).` is the original code. My understanding is that UP is a vector that points outwards from the center of the planet.

This seems to work fine, until about ~21km height where the up vector flips and the angle between up and surface_velocity becomes greater than 90° suddenly.

![image](https://user-images.githubusercontent.com/39027073/224503854-5c52918d-f3ec-473d-a630-4bf0e040f2ac.png)
This picture shows my debugging outputs. First up is the previous state, the line after ERROR is when it flips.

It looks like the purpose of the up vector is changing at some point. 

Sorry for the long post, I hope it's somewhat understandable what I am trying to do.

**Comment by EloxZ** [comment]
Keep in mind that "Up" is a field of Body. The Body Class doesn't take into account where you are, so it can't be pointing according to your position. It also contains "Right", which indicates that this is maybe the Up relative to the transform position in Unity. I'll look for it, it should be in the AutoPilot Class.

**Comment by kbleeke** [comment]
Up is a field of Vessel in this case (according to https://kontrolsystem2.readthedocs.io/en/latest/reference/ksp/vessel.html#vessel)

**Comment by EloxZ** [comment]
Yep, my bad. Then I suggest you target the body and use -autopilot.target_orientation.

**Comment by untoldwind** [comment]
Actually I'm still figuring out how to deal with the different coordinate systems in KSP2 and `HorizonUp` was most likely not the right choice. Though the flip is rather surprising I have to say. 
As a quick fix `vessel.transform.GetSimSOIBodyParentTransformFrame().ToLocalVector(vessel.SimulationObject.Position - vessel.mainBody.Position).normalized` might be the better up vector.

In KSP1 they tried to do most stuff in the vessel frame (though not consistently). In KSP2 they came up with the (imho much better) idea of an abstract `Position` and `Vector` which always have a reference system attached to it, i.e. there is no longer this ambiguity.
I'm currently working on a branch to map these new types, which will hopefully then resolve these quirky coordinate transformation issues and allow the script to decide in what reference frame to operate.

**Comment by untoldwind** [comment]
As @EloxZ has suggested. It is probably a good idea to document/dicuss this: https://github.com/untoldwind/KontrolSystem2/pull/5

**Comment by kbleeke** [comment]
>Yep, my bad. Then I suggest you target the body and use -autopilot.target_orientation.

`target_orientation` commands the autopilot the points the rocket to the given orientation (I am using this, so I'm pretty sure). Unfortunately this doesn't give a vector to the selected target body or vessel.

>vessel.transform.GetSimSOIBodyParentTransformFrame().ToLocalVector(vessel.SimulationObject.Position - vessel.mainBody.Position).normalized

I figured out how to compile the mod. This seems to give the same result with the same behavior as before. I printed both in my script so am reasonably sure, I didn't fail at compiling and installing.

I'm giving up for today but I can share my script https://gist.github.com/kbleeke/3640946c4cbd41f93db710d9a1fa1f8d

**Comment by EloxZ** [comment]
I meant the getter
https://github.com/untoldwind/KontrolSystem2/blob/6f9255cca415e76d2da3b73f91eea8f3fc2bc808/KSP2Runtime/KSPVessel/KSPVesselModule.Autopilot.cs#L39

But it's the same code you posted, so I guess we can try with vessel.SimulationObject.Telemetry.AntiTargetDirection

**Comment by untoldwind** [comment]
First of: Thanks for the script and your patience.

I can confirm that `(vessel.SimulationObject.Position - vessel.mainBody.Position)` has the same result as `HorizonUp`, so the only possible explanation would be that `vessel.transform.GetSimSOIBodyParentTransformFrame()` changes for some reason - even though it does not make much sense given the name.

Funny thing: When I debug-logged that frame it remained stable and the error did not occur, i.e. a value that depends on whether you monitor it or not ... and I thought quantum-computers where not a real thing yet.

I replaced all `vessel.transform.GetSimSOIBodyParentTransformFrame()` with vessel.mainBody.coordinateSystem` and fixed some places where the coordinate system was still ambiguous. This seems to fix the issue.

The only thing I had to tweak in your script was the `if (ang_check <= 0.1) {` condition to trigger phase 3 ... that was a bit flaky on my test-rockets.

Created a pre-release to verify: https://github.com/untoldwind/KontrolSystem2/releases/tag/v0.1.5.1

**Comment by kbleeke** [comment]
I can confirm that it works (I lied about being done). Thank for you work!

>ang_check

Anecdotally, this worked fine with 1.4 and started going wrong with my builds from source and later. But yea, I had this problem too, forgot to mention. The autopilot seems to be more sluggish, sometimes it skips ascent_stage 2 because it hasn't moved yet and sometimes it has a really hard time getting to 0 AoA to trigger stage 3. 
I guess, this also depends on the rocket (Good thing TheGreatFez's series has more chapters). I used a stock K1 with solids and wings removed this whole time.


Compiling the scripts (rebooting) also seems to take noticeably longer with 1.5.x

This issue can be closed then, I think
