### ISSUE TITLE
True Anomaly and body rotation angle?

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#46]
How do I find the true anomaly of an orbit and the body rotation angle of the planet?

**Comment by untoldwind** [comment]
As for the body rotation. I currently do not know, which of the internal fields define the starting point of a body rotation.

What I usually do in a script is snapshotting: `body.surface_normal(0,0)` and `body.surface_normal(0, 90)` at a known time.
And then rotate those by `360 * delta_time / body.rotation_period`

... maybe the `surface_normal` method should get an optional time parameter.

**Comment by untoldwind** [comment]
Not sure if the question has been answered by this.

**Comment by SodaPopinski** [comment]
Sorry I didn't follow up.  The solar prime vector is the "prime meridian" of the galaxy, or in KSP1, of the solar system.
Here's a link to how kOS handled/explained it: https://ksp-kos.github.io/KOS/bindings.html#solarprimevector

I haven't looked into doing it this way yet, as I was using it in a precision landing program I haven't tried adapting yet.  I previously applied the function in kOS for de-orbiting my SSTO, but it's a bit overkill as long as my inclination is low.

**Comment by untoldwind** [comment]
Yes, internally there a hierarchy of references frames. I guess the root frame should be available somewhere ... I will take a look.

**Comment by untoldwind** [comment]
In the 0.3.1 release I added this function to the ksp::orbit module: https://kontrolsystem2.readthedocs.io/en/latest/reference/ksp/orbit.html#galactic-origin

To my understanding this is the root reference frame of everything.

**Comment by untoldwind** [comment]
Closing this for now. Please reopen, if there is still an issue
