### ISSUE TITLE
whitespace in a fn impl leads to error

### ISSUE THREAD

**Issue by Farsyte** [untoldwind/KontrolSystem2#49]
This module compiles and works as expected:

    pub struct Named(name: string) {
        name : string = name
    }
    impl Named {
        fn get_name(self) -> string = {
            return self.name
        }
    }

However, inserting whitespace after the method name like this:

    pub struct Named(name: string) {
        name : string = name
    }
    impl Named {
        fn get_name (self) -> string = {
            return self.name
        }
    }

results in the following error message:

    ERROR: [fx\named.to(5. 9)] Parsing
    fx\named.to(5, 9): Expected '}'

(I really wish I could copy from the reboot errors to the clipboard!)

**Comment by untoldwind** [comment]
Closing this for now as have reappeared yet
