### ISSUE TITLE
How to setup a PID loop?

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#53]
How exactly do I setup a PID loop?  I can't figure it out from the documentation.  With the example below, I get an error about no constant or variable named "control."  No function if I tried just "pid_loop", "pidloop" or "PIDLoop"

use { PIDLoop } from ksp::control

...

	let tKp = 0.03		//throttle hold PID control variables
	let Ki = 0.0002
	let tKd = 0.1
	let tmin = 0.0
	let tmax = 1.0
	let throttlePID = control.pid_loop(tKp, tKi, tKd, tmin, tmax)
	
	For that last line, I've tried without "control.", pidloop, PIDLoop,

**Comment by untoldwind** [comment]
Added this example to the document: https://kontrolsystem2.readthedocs.io/en/latest/interact/pid_loop.html

I guess this can be closed then
