### ISSUE TITLE
calling through received "task : fn(MyStruct) -> float"

### ISSUE THREAD

**Issue by Farsyte** [untoldwind/KontrolSystem2#55]
Something is odd about doing an indirect call to a function
that takes a structure as a parameter.

The "s1" code shows the basic idea working when the parameter
is a float, and the "s2" is the same but changes the type of
the parameter.

Uncommenting the task(self) call triggers an error:
    ERROR: [(0, 0)] Unknown Error
        specified method is not supported

dynplan.to2:

    use { Vessel } from ksp::vessel
    use { CONSOLE } from ksp::console

    pub struct MyStruct(vessel: Vessel) {
        vessel: Vessel = vessel
    }

    impl MyStruct {
        fn s1(self, task: fn (float) -> float) -> float = {
            let dt = 0.0
            dt = task(dt)
            dt
        }
        fn s2(self, task: fn (MyStruct) -> float) -> float = {
            let dt = 0.0

    ////    dt = task(self) // UNCOMMENT HERE TO TRIGGER THE MESSAGE

            dt
        }
    }

    sync fn f1(f: float) -> float = { 1.0 }
    sync fn f2(c: MyStruct) -> float = { 1.0 }

    pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {

        const common : MyStruct = MyStruct(vessel)

        common.s1(fn (f) -> f1(f))
        common.s2(fn (f) -> f2(f))

        // These next two lines appear to be equivalent.
        common.s1(f1)
        common.s2(f2)
    }

**Comment by untoldwind** [comment]
Should compile now in 0.2.2

**Comment by Farsyte** [comment]
Question -- is the shorter form `common.s2(f2)` allowable?

Second question -- if so .. can we sneak ASYNC functions through?

**Comment by untoldwind** [comment]
Yes, the shorter for is allowed and should work.

... and I just discovered, that you currently can sneak async functions in, with pretty much unpredictable results. I'll add this to the type-checker, i.e. only sync functions are allowed as lambda for now

**Comment by untoldwind** [comment]
Should now work as indented. Reopen if there is still an issue
