### ISSUE TITLE
A case where foo.defined gets "Specified method not supported"

### ISSUE THREAD

**Issue by Farsyte** [untoldwind/KontrolSystem2#56]
This is really weird. It took a lot of tinkering to work out why
the issue kept fading in and out, as I moved things around for debug,
it behaves differently in two different contexts ...

(I've tried to reduce this down to just enough code to replicate)

    use { Vessel } from ksp::vessel
    use { CONSOLE } from ksp::console

    pub struct Sequencer(last: Option<SeqNode>) {
        last: Option<SeqNode> = last
    }

    pub struct SeqNode(next: Option<SeqNode>) {
        next: Option<SeqNode> = next
    }

    impl Sequencer {
        fn show_bug(self) -> Unit = {
            const seq : Sequencer = self

            const last : Option<SeqNode> = seq.last

            // Attempting to use "last.defined" triggers an error:
            //
            // ERROR:  [(0, 0)] Unknown Error
            //     Specified method is not supported.

    //// Uncomment the next line to trigger the error.
    ////        if (last.defined) { }

        }
    }

    pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {

        const seq : Sequencer = Sequencer(None())

        const last : Option<SeqNode> = seq.last

        // This is the same code as above, but when we do it here,
        // we do NOT get an error.

        if (last.defined) { }

    }

**Comment by untoldwind** [comment]
Should compile now in 0.2.2

**Comment by untoldwind** [comment]
Closing this for now. Reopen if error reoccures
