### ISSUE TITLE
comment in structure impl block is a compile error

### ISSUE THREAD

**Issue by Farsyte** [untoldwind/KontrolSystem2#57]
test case:

    pub struct CommentIssue() {
    }

    // oddity in KnotrolSystem2 0.2.2.0
    // placing a comment inside the "impl" block before the
    // first function declaration causes a compile error
    //     Error: [Tinker.to(45, 5)] Parsing
    //         tinker.to2(45, 5): Expected '}'
    // when the comment starts in column 5 of line 45.

    impl CommentIssue {
        // this comment is a syntax error.
        // if you remove it this file compiles.
        fn hello(self) -> Unit = {
        }
    }

**Comment by Farsyte** [comment]
the error also occurs if the comment is moved down
below the definition of the inner function.

**Comment by untoldwind** [comment]
Should be fixed in the 0.2.3 release

**Comment by untoldwind** [comment]
Seems to work as indented now. Reopen if there is still an issue.
