### ISSUE TITLE
feature request: copy from console to clipboard

### ISSUE THREAD

**Issue by Farsyte** [untoldwind/KontrolSystem2#58]
not even sure if this is remotely possible,
but if it worked, I would be able to capture
the output of my scripts (and error messages).

alternately, a way to store that text into
a log file would also work.

**Comment by untoldwind** [comment]
Turn out: Putting stuff to the clipboard is surprisingly easy for a change

**Comment by untoldwind** [comment]
Should be now included in the 0.2.3 release

**Comment by Farsyte** [comment]
working like a champ!
