### ISSUE TITLE
RCS Support

### ISSUE THREAD

**Issue by EloxZ** [untoldwind/KontrolSystem2#6]
- Adding support for RCS steering (... and actually figure out how RCS can be activated/deactivated in the first place ;) )

Doesn't this do the trick?

https://github.com/untoldwind/KontrolSystem2/blob/cc3e2b1eed591214b4a53f4f53f445ed80cb6592/KSP2Runtime/KSPVessel/KSPVesselModule.ActionGroups.cs#L22

**Comment by untoldwind** [comment]
I thought so, but as far as I can tell neither `KSPActionGroup.RCS` nor `KSPActionGroup.SAS` does anything ... or I'm not triggering the action groups right. The Lights action seems to work though.

**Comment by EloxZ** [comment]
Also, I don't think the steering is supported, it uses activeVehicle.FlightControlInput in KSP.Modules.Module_RCS.ProcessInputs(), and everything is private.

**Comment by untoldwind** [comment]
I guess steering has to be done via the `FlightCtrlState` callback just like the ThrottleManager.
There already is a corresponding `RCSTranslateManager` ... completely untested though

**Comment by EloxZ** [comment]
SetRCSEnabled in VesselComponent or TelemetryDataProvider is also private

**Comment by untoldwind** [comment]
Only place I see is in `VesselComponent.SetState` ... though I'm not sure if that is supposed to be used

**Comment by EloxZ** [comment]
In `GameManager.Instance.Game.flightInputHandler` we can override commands

**Comment by EloxZ** [comment]
```csharp
KSP.Input.FlightInputDefinition def;
if (GameManager.Instance.Game.InputManager.TryGetInputDefinition<KSP.Input.FlightInputDefinition>(out def)) {
   def.TriggerAction(GameManager.Instance.Game.Input.Flight.ToggleRCS.name);
}
```
I tried to do something like this once (but with EVAActions). It throws an invalid cast exception.

**Comment by EloxZ** [comment]
Ok this time it seems to work tho.

**Comment by untoldwind** [comment]
This is probably the correct way to trigger actions, so maybe you can integrate that into ActionGroupsAdapter as a helper function and replace all the `vessel.SetActionGroup` cases

**Comment by EloxZ** [comment]
![image](https://user-images.githubusercontent.com/45355879/224544733-49f40660-661f-4898-af2d-106db21bea4b.png)
![image](https://user-images.githubusercontent.com/45355879/224544837-3e51520e-fbee-46c5-b063-25990b6b936c.png)

Solar panels are bugged and the toggle button may be deactivated

**Comment by EloxZ** [comment]
`vessel.GetActionGroupState(KSPActionGroup.SAS)` is not reliable at all, and `vessel.GetActionGroupState(KSPActionGroup.RCS)` only if you don't use `vessel.SetActionGroup(KSPActionGroup.RCS, value)`

**Comment by untoldwind** [comment]
Lol, I just realized why the toggle via action groups is such a hazzle:

![rcs](https://user-images.githubusercontent.com/131823/224566501-237cb615-34f8-4c8f-b165-e5e5c9d86806.png)

The RCS action binds to "Toggle Crew Lights" ... with it does if you toggle it via the `TriggerAction` api.

**Comment by untoldwind** [comment]
I decided to ignore the action group and followed the trace what the Navball button is doing. This here finally seems to do the trick:
```
            public bool Rcs {
                get => GameManager.Instance.Game.ViewController.DataProvider.TelemetryDataProvider.RCSEnabled.GetValue();
                set => GameManager.Instance.Game.ViewController.DataProvider.TelemetryDataProvider.RCSEnabled.SetValueInternal(value);
            }
```

Is a bit wild
