### ISSUE TITLE
Request: LSP for syntax highlighting, linting and autocomplete

### ISSUE THREAD

**Issue by VoreckLukas** [untoldwind/KontrolSystem2#66]
As the title says an lsp to use in vim, vscode and others would be great

**Comment by untoldwind** [comment]
I was thinking about something like that.
At the moment I have a hard time deciding what framework to use for that. The parser and AST is written in C# (obviously), so to use that in a lsp I would have to use OmniSharp and jump through all the hoops of code-signing to get this working on windows. In short: This is quite a lot of effort.
A more lightweight approach would be to just use typescript, but then I essentially duplicate the parser and AST

**Comment by untoldwind** [comment]
After some consideration I would probably go with a typescript based implementation, as debugging is so much easier.
Also the parser for the LSP server should be more error-tolerant than the real thing.
Progress is tracked here: #80

**Comment by arcykojot** [comment]
Will it be available for VS 2022?

**Comment by OverloaderV** [comment]
> Will it be available for VS 2022?

As far as I understand lsps One lsp should work with every client that implements the protocol. So a lsp that works with vscode *should* work with vim and anything else that implements the protocol. But i'm not an expert

**Comment by untoldwind** [comment]
At the moment I am planing to provide the LSP server itself and a corresponding client for VSCode.
I do not really know all to much about VS 2022 to estimate how easy it might be to integrate an LSP server. Though the protocol is standardized and maintained by Microsoft.

**Comment by VoreckLukas** [comment]
> Though the protocol is standardized and maintained by Microsoft.

As much as i dont like microsoft, I love that vscode introduced lsp which revolutionized (n)vim

**Comment by untoldwind** [comment]
There now is an experimental (i.e. it still gets things wrong) LSP server: https://github.com/untoldwind/KontrolSystem2/releases/download/v0.4.0.1/lsp-server.js

Here is a minimal neovim `init.lua` I use to test if it is working for other editors as well:
```lua
local lspconfig = require('lspconfig');
local configs = require('lspconfig.configs');

configs.to2 = {
  default_config = {
    cmd = { 'node', 'FULL_PATH_TO/lsp-server.js', '--stdio' },
    filetype = 'to2',
    root_dir = lspconfig.util.root_pattern('.git', '.'),
  },
}

lspconfig.to2.setup {
  on_attach = on_attach,
  capabilities = capabilities,
}

vim.lsp.set_log_level("debug")

vim.api.nvim_set_hl(0, "@lsp.type.keyword", { link="Keyword" })
vim.api.nvim_set_hl(0, "@lsp.type.number", { link="Number" })
```
