### ISSUE TITLE
To2 compiler reads files with the ".to2~" extension

### ISSUE THREAD

**Issue by Farsyte** [untoldwind/KontrolSystem2#69]
When rebooting, and compiling the .TO2 source files, the compiler
also reads files with the ".to2~" extension. This is awkward since
a popular editor (emacs) saves the previous version there.

Can the compiler please only read files with the correct extension?

**Comment by untoldwind** [comment]
Who would have guessed that
`Directory.GetFiles(baseDir, "*.to2", SearchOption.AllDirectories)`
also matches to `.to2~` (or `.to2<anything>`).
Those pranksters at Microsoft, always good for a laugh.

Will be fixed in the next release.

**Comment by Farsyte** [comment]
Confirmed fixed in release 0.3.3.1

Thank you! This really helps my development loop when I reach out to use Emacs to do the things it does better than VS-Code ;)
