### ISSUE TITLE
trigger_staging stages too much with a partial flame out

### ISSUE THREAD

**Issue by kbleeke** [untoldwind/KontrolSystem2#7]
While messing with the K1 and gravity turn I noticed that `trigger_staging` stages my main engine while it's still running right after booster separation. As far as I can tell, it checks whether the next stage has engines and if not, stages again. I imagine the purpose is to make rocket work where the decoupler and next engine are in separate stages. 

I ended up doing the following to detect running engines:

```
pub fn trigger_staging(vessel : Vessel) -> Unit = {
    if(vessel.staging.current == 0) return

    let flameout = has_flameout(vessel)
    let ignited = has_ignited(vessel)

    if (flameout || !ignited) {
        CONSOLE.print_line(" stage " + vessel.staging.current.to_string() + " ignited " + ignited.to_string() + " flameout " + flameout.to_string())
        wait_until(fn() -> vessel.staging.ready)
        vessel.staging.next()
    }
}
```

Now this stages, if there is a flameout or if there are not running engines. Booster separation only causes one staging as there is still a running engine. The case when we need to find the next engine after a decoupler is handled automatically, if this funciton is called every tick. It will stage once for flameout and then again on the next tick as no engines are running.

I tried to do this logic in a loop to stage everything in the same tick but the vehicle state didn't seem to update between interations.

**Comment by EloxZ** [comment]
Maybe it's because it's not a sync function? and it's running coroutines... just guessing. Also, you can try with if (vessel.staging.ready) in the loop

**Comment by untoldwind** [comment]
I also noticed that the engine states linger in their previous state for a "short moment" right after `vessel.staging.next()` has been triggered. I tried to mitigate this be inspecting the next stage beforehand.

Do you buy chance not have the latest version of the `staging.to2`:

```
pub fn trigger_staging(vessel : Vessel) -> bool = {
    if(vessel.staging.current == 0) return false

    let needs_staging = has_flameout(vessel)
    if(needs_staging) {
        const stage = vessel.staging.current
        // Only some engines had a flameout
        const is_partial_flameout = has_still_running(vessel)
        // The next stage does not trigger any engines
        const next_has_engine = if(stage > 0) has_engine_in_stage(vessel, stage - 1) else false
        CONSOLE.print_line("Trigger next stage")
        wait_until(fn() -> vessel.staging.ready)
        vessel.staging.next()

        if(stage > 0 && !is_partial_flameout && !next_has_engine) {
            CONSOLE.print_line("No engine staged, trigger next")
            wait_until(fn() -> vessel.staging.ready)

            vessel.staging.next()
        }
    }

    needs_staging
}

pub sync fn has_flameout(vessel : Vessel) -> bool = {
    for(engine in vessel.engines)
        if(engine.has_ignited && engine.is_flameout)
            return true
    false
}

pub sync fn has_still_running(vessel : Vessel) -> bool = {
    for(engine in vessel.engines)
        if(engine.has_ignited && !engine.is_flameout)
            return true
    false
}

pub sync fn has_engine_in_stage(vessel : Vessel, stage: int) -> bool = {
    for(part in vessel.staging.parts_in_stage(stage)) {
        if(part.is_engine)
            return true
    }
    false
}
```

**Comment by kbleeke** [comment]
Right, I didn't see that this was updated in 1.5. I have it, just didn't check after updating. Thanks
