### ISSUE TITLE
std::land::landing_simulation not working?

### ISSUE THREAD

**Issue by PyroSA** [untoldwind/KontrolSystem2#70]
I took a quick stab at spinning up a landing simulation to work out a landing trajectory.

init_simulation gives me an error:
```
Module land_ahoy terminated with:
Method `STD__LAND__LANDING_SIMULATION_ReentrySimulation..ctor()' is inaccessible from method `LAND_AHOY+AsyncFunction_main_flight.PollValue()'
```

My short scribble script:
```
use { Vessel } from ksp::vessel
use { CONSOLE } from ksp::console
use { current_time } from ksp::game
use { init_simulation, ReentrySimulation } from std::land::landing_simulation
use { safe_speed_policy } from std::land::speed_policy

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
    CONSOLE.clear()
    CONSOLE.print_line("speed policy")
    let speed_policy = safe_speed_policy(
        vessel.orbit.reference_body.radius,
        vessel.orbit.reference_body.grav_parameter,
        1.0
    )
    
    CONSOLE.print_line("init")
    let sim = init_simulation(
        vessel, 
        current_time(),
        1.0, 0.1,
        1.0,
        100,
        speed_policy
    )

    // >>>>> ERROR <<<<<<<<<

    CONSOLE.print_line("run")
    let traj = sim.run()
}
```
---
KSP 0.1.2
KS 0.3.3

**Comment by untoldwind** [comment]
Quick and dirty fix: Move the script from the "to2Local" folder to the "to2" folder.

I have to take a deeper look at the generated code to understand this problem (both the struct and constructor are marked as public, so it not obvious why this exception occurs)

**Comment by untoldwind** [comment]
Should be fixed in 0.3.3.2

**Comment by PyroSA** [comment]
Confirmed - Works in 0.3.3.2 - thanks 😁 

It seems to run over the limit (to be expected) when in orbit.
If I set it to only run when periapsis is below the surface I seem to get results, will dig in to those a bit more.

**Comment by untoldwind** [comment]
Yes, the periapsis has to be beneath sealevel to get a valid prediction from the reentrysimulation.
This could probably be fixed by ending the ODE at the lowest point instead of "ground-hit".

As for unstopable scripts: Might be an issue with background threads, I will look into it.
