### ISSUE TITLE
Could use some descriptions / help on Autopilot modes

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#71]
The documentation doesn't have any description of the autopilot modes.  Prograde, retrograde, maneuver, etc are obvious.  I'm assuming target is to the target vessel.  If I want to point in a specific direction, I'm not sure if I should use Navigation, StabilityAssist, or Autopilot.

It might also be useful to specify when to use vessel.autopilot.lock_direction = vessel.heading_direction(x,y,z) vs. vessel.autopilot.target_orientation = vessel.heading_direction(x,y,z).vector.  I assume lock_direction gives the additional "up" information so you can have your cockpit in a plane facing upwards.

https://kontrolsystem2.readthedocs.io/en/latest/reference/ksp/vessel.html#autopilot

**Comment by untoldwind** [comment]
I added some basic documentation to the `AutopilotMode` enum (and some of the other enums), but a lot of the inner workings of the SAS system are still unclear. E.g. at the moment I can not say if there is any difference between `AutopilotMode.Autopilot` and `AutopilotMode.Navigation`, it looks like the behave identical, but it is very well possible that I overlooked something.

What is more or less known:
* `AutopilotMode.Autopilot` and `AutopilotMode.Navigation` align the vessel to the `vessel.autopilot.target_orientation` vector, but ignores the roll of the vessel (just tries to stop it). `vessel.autopilot.lock_direction` is ignored (as far as I can tell).
* `AutopilotMode.StabilityAssist` essentially just tries to stop all rotation of the vessel. `vessel.autopilot.target_orientation` is ignored (as far as I can tell).  `vessel.autopilot.lock_direction` temporarily overrides the desired rotation/direction of the vessel (including roll), but will reset with each tick of the physics engine (as far as I can tell).
* All the other modes behave like  `AutopilotMode.Autopilot` and `AutopilotMode.Navigation`  expect that `vessel.autopilot.target_orientation` is ignored at the corresponding orbit-vector is used.

**Comment by untoldwind** [comment]
I added an adapted version of the kOS steering manager in the 0.3.3.3 release.

```rust
use { Vessel } from ksp::vessel
use { CONSOLE } from ksp::console
use { sleep } from ksp::game
use { control_steering } from std::control::steering

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
    const control = control_steering(vessel)

    control.set_heading(30, 20, 10) // this is angle_north, pitch_above_horizon, roll

    for(i in 0..1000) {
        sleep(0.1)
        control.controller.print_debug()  // Print internal state of the controller
    }

    control.release()
}
```
Inner workings are here: https://github.com/untoldwind/KontrolSystem2/blob/master/KSP2Runtime/to2/std/control/steering.to2

I was just able to do some basic testing so far.

**Comment by untoldwind** [comment]
Closing this for now. Just reopen if there are further questions.
