### ISSUE TITLE
question - how to use the FlightCtrlState?

### ISSUE THREAD

**Issue by ColJay** [untoldwind/KontrolSystem2#72]
Trying to figure out how to access the FlightCtrlState of the active vessel. I've tried exposing the FlightCtrlState in a similar way to the Autopilot - but there's an error stating it doesn't exist.

I've tried to access the variables of the state directly off the vessel, but they don't exist. I've tried to figure it out from the code, but i don't really understand the construct for the FlightCtrlState (I'm no programmer - esp not c#)

Any guideance? Trying to twek my throttle controls for hover as the expected thrust values don't quite match in game.

Thanks for the awesome work so far!

**Comment by untoldwind** [comment]
A simple way is to use the override methods: https://kontrolsystem2.readthedocs.io/en/latest/interact/control.html#use-input-override-methods
(Note: These values will reset to zero on each tick of the physics engine)

More sophisticated is using the control managers: https://kontrolsystem2.readthedocs.io/en/latest/interact/control.html#control-manager

The reason for this is that the FlightCtrlState is something of a temporary struct that is reset on each game-update. Internally the control managers add an autopilot hook that is called on every update right before the FlightCtrlState is read.

Simple examples:
```rust
let manager = vessel.set_throttle(0.5) 

sleep(5) // script is sleeping for 5 seconds, but hook is active and sets throttle to 50%

manager.release() // hook is removed and throttle goes back to 0
```

```rust
let manager = vessel.set_steering(vec3(0.1, 0.2, 0.3)) 

sleep(5) // script is sleeping for 5 seconds, but hook is active and sets pitch to 10%, yaw to 20% and roll to 30%

manager.release() // hook is removed and controls go back to 0
```

**Comment by ColJay** [comment]
Ahhh - ok - penny drops. Use the manager get the info, not the vessel directly. Thanks

**Comment by untoldwind** [comment]
Closing this for now. Just reopen if there are further questions.
