### ISSUE TITLE
landing_simulation path in celestial frame seems... off?

### ISSUE THREAD

**Issue by PyroSA** [untoldwind/KontrolSystem2#74]
I'm not sure how to describe this, as I'm not familiar with all these different frames.
Here we have a almost vertical landing:
![Screenshot (29)](https://user-images.githubusercontent.com/3801259/232921958-e08ac4e5-e99d-4bad-b01c-e67efc21651f.png)

The cross is the predicted lon/lat, and pretty accurate.
The path is plotted directly as a debug path.
This seems to go off to the side in the orbital velocity direction?

High in orbit, this hardly matters, as the difference between orbital and surface isn't that great, but as you get closer to land, there is a MAJOR difference.

---

Another weird-ness is the the max_t is only like 6.3 seconds inside the atmosphere of kerbin for some reason.
Accumulating dt on to the sim.t allows me to get a time to land/impact number, but it's capped by this max_t.

With a burn time in excess of 20 seconds, this did not give me a hint at when to start burning to bleed off speed.

A drop with a periapsis of -200km takes at least 3 minutes to hit the ocean.

---

**Comment by untoldwind** [comment]
Do not forget that the `ReentrySimulation` was created for vacuum and completely ignores any drag. I have a hard time remembering the reasoning behind the `max_t` calculation (something about the period of a free-fall trajectory I guess).
For the most part it is only there to end the ODE solver in case there is no ground hit, so you can tweak that according to your needs.

As for the reference frames: The calculation is done in the celestial frame of the body which is the non-rotating frame, which is good for any kind of orbital calculations. Close the the ground it might be feasible to switch to the `body_frame` which is relative to the service.
E.g. 
```
vessel.global_velocity.to_local(vessel.main_body.celestial_frame)
```
should be the orbital velocity and
```
vessel.global_velocity.to_local(vessel.main_body.body_frame)
```
should be the surface velocity.

There might be another problem though: The `ReentrySimulation` does not take the current orientation of the vessel into account (i.e. the current vector of thrust), it is implicitly assumed that the vessel is just able to arbitrarily change its velocity in any direction. At high altitude this is mostly irrelevant, but close to the ground there just is not enough time to realign the ship with every prediction.

The best tactic I came up with so far is to use the `ReentySimulation` to slightly overshoot the desired target and kill the vertical surface velocity at a high enough altitude right above(ish) the desired landing spot.
