### ISSUE TITLE
Ambigious error:  Negative stack count

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#78]
Rebooted in 00:00:02.3043816

ERROR: [(0, 0)] Unknown error
Negative stack count at stloc.2 offset 62

No details on which program or where the error is coming from when I forgot to include a parameter

pub fn get_hover_throt (vessel: Vessel) -> float = {
	let vertpit = abs(vessel.facing.vector.angle_to(vessel.up))
	let thrustcorrect = 1/math::cos_deg(vertpit)
	thrustcorrect*((vessel.mass)*grav_force() / vessel.available_thrust)    //forgot vessel parameter, causing crash
}

pub fn grav_force (vessel: Vessel) -> float = {
	vessel.orbit.reference_body.grav_parameter / pow((vessel.orbit.reference_body.radius + vessel.altitude_sealevel),2.0)
}

**Comment by untoldwind** [comment]
Should be fixed in 0.3.4
The script will still fail to compile, but there should now be a correct error message

**Comment by untoldwind** [comment]
Closing this for now.
Just re-open if it occurs again
