### ISSUE TITLE
Vessel field for landed/splashed/flying/orbit?

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#8]
Is there a way to determine the state of the craft?  Right now I'm getting the difference between the ground offset and terrain altitude to determine if it landed, but the difference varies quite a bit between horizontal and vertical craft.

**Comment by EloxZ** [comment]
It's not been added yet. I guess you can check if vertical_speed is 0 as a workaround.

**Comment by SodaPopinski** [comment]
> It's not been added yet. I guess you can check if vertical_speed is 0 as a workaround.

I was thinking about that, but it be a problem with hovering craft.

Anyway, no hurry.  Game isn't really out yet.

**Comment by untoldwind** [comment]
I added a `vessel.situation` property in the 0.1.6 release. This probably fixes this issue.

**Comment by untoldwind** [comment]
I am closing this for now in favor of #29

`vessel.stitutation` provides the requested information, but the returned strings are somewhat "fuzzy":
    PreLaunch
    Landed 
    Splashed
    Flying
    SubOrbital
    Orbiting 
    Escaping 
    Unknown
