### ISSUE TITLE
Invert control surfaces?

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#85]
Is there anyway to invert or at lest de-activate the control surfaces?

I'm working on a Return to Landing Site script, and the tail fins do the opposite of what I need when flying backwards.

**Comment by untoldwind** [comment]
There currently is no binding for control surfaces.
Internally there are some function that might do the trick: E.g. `Module_ControlSurface.SetControlServiceInvertControlState`

I will do some experiments with that

**Comment by SodaPopinski** [comment]
Awesome!
