### ISSUE TITLE
Is it possible to run scripts on two separate craft?

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#86]
After I decouple my craft, I've got two craft.  I'd like to be able to run two different scripts on each one.  Any way to do this at this point?

**Comment by untoldwind** [comment]
I added this to the 0.4.1.1 release.
There is now also a ´vessel.make_active()´ method to switch the active vessel in a script.

Activating and controlling RCS on a non-active vessel is still not working. This might be a bug/missing-feature in the game itself. There seems to be some code in the Module_RCS that prevents flight control input being processed if the vessel is not the active vessel.

**Comment by untoldwind** [comment]
In the 0.4.1.2 I added some functions to launch scripts programmatically:

```rust
use { Vessel, get_vessels_in_range } from ksp::vessel
use { MAINFRAME } from ksp::game

pub fn main_flight(vessel: Vessel) -> Result<Unit, string> = {
    const other = get_vessels_in_range().find(fn(v) -> v.name == "Kerbal K2-12").ok_or("Other not found")?

    const dockit = MAINFRAME.find_process("dock").ok_or("Dock not found")?

    dockit.start(other)
}
```
This should do the same as launching the "dock" script for the vessel with name "Kerbal K2-12" via the UI.
But as said before: Controlling a vessel which is not active might lead to some unexpected behavior.
