### ISSUE TITLE
Documentation for AND / OR operators

### ISSUE THREAD

**Issue by SodaPopinski** [untoldwind/KontrolSystem2#9]
I was use to using "and" and "or" from kOS and Python.  Since I believe a lot of To2 is based on C#, I looked up "and" is && and "or" is probably ^ or ||

**Comment by untoldwind** [comment]
Added documentation for all the operators: https://kontrolsystem2.readthedocs.io/en/latest/language/operators.html

**Comment by untoldwind** [comment]
Closing this for now
