### ISSUE TITLE
VSCode Extension doesn't seem to recognise modules in local user path - How to configure?

### ISSUE THREAD

**Issue by plonk-75** [untoldwind/KontrolSystem2#93]
I've tried the `to2-syntax-0.0.6.vsix` and I really like it! Sadly, since I moved my own stuff to another location than the standard to2 folder, I'm unable to make it recognise my modules. Below is a screenie of how it looks in VSC. The path is configured under `## Path of the local user library` in `com.github.untoldwind.KontrolSystem2.cfg` and the programs works in KSP. I can't find any path settings in `settings.json`.

How do I make the VSC Extension search in custom paths? Or even better, maybe additionally the paths in the VSC workspace? 

![module_not_found](https://github.com/untoldwind/KontrolSystem2/assets/132899233/1c47a1c7-389d-4d97-a519-be76ab7aa6ef)
EDIT/addendum: Noticed that a) the settings.json has nothing to do with KS2 - sorry for spreading my wrong assumptions again, b) local paths aren't the cause, as the same problem occurs with the default location, too.

**Comment by untoldwind** [comment]
Should be fixed in this release: https://github.com/untoldwind/KontrolSystem2/releases/download/v0.4.1.3/to2-syntax-0.0.7.vsix
The "libraryPath" in the settings should point to the "to2" folder shipped with the mod. It should still work if left blank, but then "goto definition" will not work for anything in "std::"

**Comment by plonk-75** [comment]
Can't confirm. Having this config:
```
[Paths]
stdLibPath = D:\SteamLibrary\steamapps\common\Kerbal Space Program 2\BepInEx\plugins\KontrolSystem2\to2
localLibPath = D:\SteamLibrary\steamapps\common\TO2-Local
```
Both paths are double checked and correct, but I suppose they are for the KSP2 plugin only. 

The VSIX config (User + Workspace) has a double checked path as well:
`D:\SteamLibrary\steamapps\common\Kerbal Space Program 2\BepInEx\plugins\KontrolSystem2\to2 
`
It recognises the std:: modules fine, and goto definition works for these modules. Strangely, even if I change the VSIX lib config to some non existing path (User + Workspace), jumping to std module definitions works. VSIX config seems to have no influence whatsoever (?). 

Anyway, there are some changes and oddities with 0.0.7. It's prolly for the best having a look at these screenies:
![to2-syntax-0 0 7vsix_module_funcs](https://github.com/untoldwind/KontrolSystem2/assets/132899233/fe281a0c-4047-4d6f-8353-dc516264765b)

Def of plotOrbit is as follows:
```
pub sync fn plotOrbit(o: Orbit, color: RgbaColor = GREEN, fromDeg: float = -180.0, toDeg: float = 180.0) -> DebugPath = { ... }
```
So with 0.0.7 functions in local modules are recognised, although not quite completly.

Regarding structs in modules, these are not recognised as desired:
![to2-syntax-0 0 7vsix_module_pub_struct](https://github.com/untoldwind/KontrolSystem2/assets/132899233/843c8cf7-1080-4b4f-b969-b02c25c693b2)

The struct is defined as:
```
pub struct SecondOrderSystem(f: float, ζ: float = 1.0, r: float = 1.0, x0: float = 0.0) { ... }
impl SecondOrderSystem { ... }
```
and the code for both work in KSP2. 

There is an additional oddity using Linux, where the VSIX does not recognise anything of my local modules. There it still looks like this example, note the different location of wiggly lines:
![to2-syntax-0 0 7vsix_mint](https://github.com/untoldwind/KontrolSystem2/assets/132899233/7721c3b8-842e-4ee2-a2af-2684477facda)
Under linux the two paths, to2 and to2local, are mounted into the file system, but of course there's no way to access anything KSP2 related outside these two paths (VirtualBox Shared Paths).
