### ISSUE TITLE
Order of operations wrong or unintended exponent "feature".

### ISSUE THREAD

**Issue by lsedberg** [untoldwind/KontrolSystem2#95]
When it comes to order of operations, exponents comes before division. However, in my script it doesn't?

The documentation doesn't mention the usage of `^` to raise a number to any power (only as bit-xor operator between integers), so is this an unintended "feature"? Either the order of operations are wrong, or `^` is not intended to be used to raise a number to a power. If it is not intended, as to not confuse it with the bit-xor operator, it could for example be replaced with `**`, or removed completely (as we have `core::math::pow`).

I expect g_3 to output the same value as g_1 and g_2, but it instead outputs the same value as g_4 and g_5.
![image](https://github.com/untoldwind/KontrolSystem2/assets/80771288/566f8d4e-9389-4364-8258-1652edb21eb3)

![image](https://github.com/untoldwind/KontrolSystem2/assets/80771288/3366fd04-a0c2-4b5c-884e-d834c188bb55)

CAUTION, this is using the `v0.4.1.3` version of Kontrol System 2 in KSP 2 `v0.1.3.1`, as version `v0.4.2` and `v0.4.2.1` of Kontrol System 2 apparently does not work for me, (mod error).

**Comment by untoldwind** [comment]
Currently the `^` operator is implemented as bit-xor (similiar to C# or Java)
But I guess this has very limited usecases inside an autopilot script ;)

... I will change the operator to be equivalent to `pow`

**Comment by untoldwind** [comment]
Should be fix in 0.4.2.2

**Comment by plonk-75** [comment]
> ... I will change the operator to be equivalent to `pow`

Please don't remove the possibility to perform bit operations on integer values. Since the `pow` "version" of the `^` operator was previosly undocumented, I'd consider this as a step in the wrong direction if it reduces the options of programmers.

**Comment by untoldwind** [comment]
I guess the inconsistent behavior with float values was somewhat more important. If there is a need for a bit-xor operation it would be possible to introduce that as either a function or different kind of operator.

**Comment by plonk-75** [comment]
I essentially agree with both of you. 

- wrong operator precedence simply has to be corrected
- use cases _seem_ rare at first glance
- `(...)^2` is more convenient both for writing and reading than `pow(...,2)`
- the `^` operator probably occurs more often as a power operator so convenience is a good thing

What I am concernded about is _loosing_ the ability to do xor ops. I do not care much about if it's a function or an operator or which symbols the operators get in the end. 

As for UCs, there's one that immediately comes to my mind, which are bitfields to either represent combined states or arguments to functions. I think it is much more readable and convenient to write something along the lines of

`fn(SomeThing: a, int options) {...}`
than
`fn(SomeThing: a, bool: optionA, bool: optionB, bool: optionC, ...) {...}`

Same holds for state info.
\*sigh* Maybe I had too much of assembly language and low level C/C++ in my early days. :-)

**Comment by untoldwind** [comment]
Introduce a new operator `**` for `pow` is probably the best compromise to keep the language "compatible" with other languages.
I will look into it over the weekend

**Comment by untoldwind** [comment]
Changed this in 0.4.3:
`^` is back as bit-xor, but only defined for `int`
New operator `**` for pow (with higher precedence than `*` and `/`) defined for int and float

**Comment by untoldwind** [comment]
Closing this for now. Just reopen if there are further problems of this nature
