### ISSUE TITLE
KontrolSystem2 Icon doesn´t show in the drop down menu anymore

### ISSUE THREAD

**Issue by LanzAlex** [untoldwind/KontrolSystem2#96]
Hy,

I don´t know much about programing, so I have dived a bit deeper into this and then wanted to return on scripting in TO2 language.
Now I have discovered, that the KS2 Icon does not show up anymore, I´ve installed all the necessarry mods that are recommended, I´ve updated them, removed all, installed it manually, removed all installed it through ckan, but still it doesnt work. In BeqInEx it is listed as an Errot, but not why. Since I don´t read that anybody else is experiencing this and that I have tried everything I could I ask for help.

Thank you in advance

**Comment by plonk-75** [comment]
Ran into the same problem without CKAN. A look into\Kerbal Space Program 2\BepInEx\LogOutput.log showed this:
```
[Error  :   BepInEx] Could not load [KontrolSystem2 0.4.2.1] because it has missing dependencies: com.github.x606.spacewarp (v1.3.0.1 or newer)
```
While in spacewarp-release-1.3.0.3.zip (latest as to time of writing), swinfo.json says:
```
  "spec": "1.3",
  "mod_id": "com.github.x606.spacewarp",
  "name": "Space Warp",
  "author": "Space-Warp Team",
  "description": "Space-Warp is an API for KSP2 mod developers.",
  "source": "https://github.com/SpaceWarpDev/SpaceWarp",
  "version_check": "https://raw.githubusercontent.com/SpaceWarpDev/SpaceWarp/main/SpaceWarpBuildTemplate/swinfo.json",
  "version": "1.3.0",
```
And in BepinEx's LogOutput.log one finds:
```
[...]
[Info   :   BepInEx] Loaded 1 patcher method from [SpaceWarpPatcher 1.3.0.0]
[...]
```
So SpaceWarp 1.3.0.3 identifies itself as 1.3 while KS2 requires(!) 1.3.0.1 which it can't find.
In summary, it seems the versioning of the dependencies is not correct.

**Comment by LanzAlex** [comment]
Thank you so much for your response...
so it is nothing that I could edit to make it work, if I understand your words correctly?

Have a nice day

**Comment by plonk-75** [comment]
I _think_ there's nothing we users can do at this point. I just added some evidence to show that this issue is (at least to my conclusion, call it "educated guess") not a problem on the user side, and wanted to confirm your observation. Maybe I'm wrong. Let's see what @untoldwind diagnoses about this issue. :)
BTW, other users have suspiciously similar issues, see forum -> [KS2 Release Thread](https://forum.kerbalspaceprogram.com/topic/214543-release-kontrolsystem2-042/?do=findComment&comment=4299584)

**Comment by untoldwind** [comment]
It looks like the version of SpaceWarp slightly outdated on spacedock.
Please re-check with the current version of SpaceWarp (1.3.1), it should fix the problem

**Comment by plonk-75** [comment]
Confirmed, using SpaceWarp Version (1.3.1 in a `spacewarp-release-1.3.0.zip`!) does the job. The SpaceWarp Team released the new version just at the right time! :-)

**Comment by LanzAlex** [comment]
Yes, the new Space Warp did the job, big thanks to all of you :-)
