### ISSUE TITLE
ksp::telemetry::add_time_series() not working

### ISSUE THREAD

**Issue by plonk-75** [untoldwind/KontrolSystem2#97]
The example code from [simple-example](https://kontrolsystem2.readthedocs.io/en/ui_rewrite/interact/telemetry.html#simple-example) does not work.

Script to reproduce error:
```RUST
use { Vessel } from ksp::vessel
use { add_time_series } from ksp::telemetry
use { cos_deg } from core::math

pub fn main_flight( vessel: Vessel) -> Result<Unit, string> = {
    let cos = add_time_series("Cos", 0, 0.1)
    for(i in 0..20000) {
        cos.add_data(i * 0.2, cos_deg(i / 20.0))
    }
}
```

Result:
```
>>>>> ERROR <<<<<<<<<

Module plonk::testgraphs terminated with:
Object reference not set to an instance of an object
```

Expected result: 
No error, working example

Reduced to the most simple form:

```RUST
pub fn main_flight( vessel: ksp::vessel::Vessel) -> Result<Unit, string> = {
    let cos = ksp::telemetry::add_time_series("Cos", 0, 0.1)
}
```
Still responding with the same error message.

**Comment by untoldwind** [comment]
This must have happened during one of the refactoring/cleanup rounds ... totally avoidable. Lesson learned: Don't trust your IDE too much.
Should work again in 0.4.2.3

**Comment by plonk-75** [comment]
Fix confirmed but there's still an issue regarding probably wrong alpha transparency making rendered text such as values and labels unrecognisable. See screenies:
![telemetry_window](https://github.com/untoldwind/KontrolSystem2/assets/132899233/dc3322eb-1bc8-4477-b275-c6925d25ed27)
![telemetry_window_plot](https://github.com/untoldwind/KontrolSystem2/assets/132899233/53d98ece-f2b5-486f-a778-5c921a9ced57)
