### ISSUE TITLE
Telemetry window: rendered text is unrecognisable

### ISSUE THREAD

**Issue by plonk-75** [untoldwind/KontrolSystem2#98]
Something's wrong with rendering text inside the telemetry window canvas. See screenshots:
![telemetry_empty](https://github.com/untoldwind/KontrolSystem2/assets/132899233/2b4f1754-e8fe-41e9-97b8-4994dd44a8c9)
![telemetry_plot](https://github.com/untoldwind/KontrolSystem2/assets/132899233/5b1e5b45-01d1-4b06-8e0f-d4824f5e5ea3)

**Comment by untoldwind** [comment]
Looks like with the last game update the TextMeshPro shader was updated as well.
There is probably still room for improvement, but the labels should be readable again in 0.4.2.4

... still not sure why this only happens after a resize though

**Comment by plonk-75** [comment]
No need for a resize on my side, otherwise I'd have the info added. I play in windowed mode with borders though, so I can do something on my other monitors without KSP hiding when losing focus.

**Comment by plonk-75** [comment]
Aaaah. ♬I can see clearly ♫ now, the blur has gone ♪... :-)
Fix confirmed!

**Comment by untoldwind** [comment]
I was somewhat imprecise there: I meant the resizing of the telemetry window in the game.

I bit more in detail:
The graph is drawn inside a RenderTexture, when the telemetry window is resized, the texture is resized accordingly, so that (in theory) the resolution of the texture always matches with the screen resolution ... but somewhere in there the parameters of the text shader get messed up.
Unluckily this is really hard to debug.

**Comment by plonk-75** [comment]
>  I meant the resizing of the telemetry window in the game.

That's what I understood in the first place. But there was no need to resize any window, neither the KS2 windows nor the KSP main window, to blur out the text on my side - double checked. 
I (again) assumed, that most people play in exclusive fullscreen mode, what makes my habit of playing in a bordered windowed mode a possibly relevant difference. So I added the info. 
Besides, it does not _look_ as if the texture resolution itself was wrong, because the details are there. You can make the text in the screenshots perfectly readable by increasing contrast and reducing brightness (e.g. in gimp). I just did that with one of the above screenshots:
![telemetry_contrast](https://github.com/untoldwind/KontrolSystem2/assets/132899233/c954be4a-319f-4fe2-8b69-78f78deb156a)
To me it looks as if the font is made of lines, and the pixels' brightness relate to a distance field with a wrong factor/threshold. (speculations are fun, excuse me)

Anyway, it's fixed now and that's what matters most. Thank you for your explanation and efforts to keep this thing going!
